import { allFullNameBonusList, BonusType } from "netim2-shared";

export const bonus6_7BonusList: BonusType[] = [
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.VALOR_DE_ATAQUE,
    bonus_ref_name: 'ad',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['general.ad'] },
    values: { min: 10, max: 25 },
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.VALOR_DE_ATAQUE_MAGICO,
    bonus_ref_name: 'ap',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['general.ap'] },
    values: { min: 10, max: 25 },
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.RESISTENCIA_AL_VENENO,
    bonus_ref_name: 'def_veneno',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.def_veneno'] },
    values: { min: 1, max: 5 },
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.RESISTENCIA_AL_FUEGO,
    bonus_ref_name: 'def_incendio',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.def_incendio'] },
    values: { min: 1, max: 5 },
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.RESISTENCIA_AL_SANGRADO,
    bonus_ref_name: 'def_sangrado',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.def_sangrado'] },
    values: { min: 1, max: 5 },
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.FUERZA_CONTRA_CHAMANES,
    bonus_ref_name: 'chaman',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.chaman'] },
    values: { min: 5, max: 10 },
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.FUERZA_CONTRA_GUERREROS,
    bonus_ref_name: 'guerrero',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.guerrero'] },
    values: { min: 5, max: 10 },
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.FUERZA_CONTRA_SURAS,
    bonus_ref_name: 'sura',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.sura'] },
    values: { min: 5, max: 10 },
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.FUERZA_CONTRA_NINJAS,
    bonus_ref_name: 'ninja',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.ninja'] },
    values: { min: 5, max: 10 },
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.DEFENSA_CHAMAN,
    bonus_ref_name: 'def_chaman',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.def_chaman'] },
    values: { min: 3, max: 5 },
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.DEFENSA_GUERRERO,
    bonus_ref_name: 'def_guerrero',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.def_guerrero'] },
    values: { min: 3, max: 5 },
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.DEFENSA_NINJA,
    bonus_ref_name: 'def_ninja',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.def_ninja'] },
    values: { min: 3, max: 5 },
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.DEFENSA_SURA,
    bonus_ref_name: 'def_sura',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.def_sura'] },
    values: { min: 3, max: 5 },
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.MAX_HP,
    bonus_ref_name: 'hp',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['general.hp'] },
    values: { min: 50, max: 800 },
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.VELOCIDAD_DE_ATAQUE,
    bonus_ref_name: 'va',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['general.va'] },
    values: { min: 1, max: 10 },
    valid: ['arma'],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.FUERZA_CONTRA_MONSTRUOS,
    bonus_ref_name: 'monstruos',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.monstruos'] },
    values: { min: 5, max: 20 },
    valid: ['collar'],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.RESISTENCIA_AL_DAÑO_DE_HABILIDAD,
    bonus_ref_name: 'def_hab',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.def_hab'] },
    values: { min: 1, max: 5 },
    valid: ['armadura'],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.RESISTENCIA_AL_DAÑO_DE_MEDIA,
    bonus_ref_name: 'def_media',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.def_media'] },
    values: { min: 1, max: 5 },
    valid: ['armadura'],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.STR,
    bonus_ref_name: 'STR',
    effects: { type: 'attribute_modifier', operation: 'flat', target: 'atribute.STR.bonusPoints' },
    values: { min: 1, max: 10 },
    valid: ['brazalete'],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.INT,
    bonus_ref_name: 'INT',
    effects: { type: 'attribute_modifier', operation: 'flat', target: 'atribute.INT.bonusPoints' },
    values: { min: 1, max: 10 },
    valid: ['brazalete'],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.DEX,
    bonus_ref_name: 'DEX',
    effects: { type: 'attribute_modifier', operation: 'flat', target: 'atribute.DEX.bonusPoints' },
    values: { min: 1, max: 10 },
    valid: ['brazalete'],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.VIT,
    bonus_ref_name: 'VIT',
    effects: { type: 'attribute_modifier', operation: 'flat', target: 'atribute.VIT.bonusPoints' },
    values: { min: 1, max: 10 },
    valid: ['brazalete'],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.ROBO_DE_VIDA,
    bonus_ref_name: 'robo_vida',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.robo_vida'] },
    values: { min: 1, max: 5 },
    valid: ['botas'],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.PROB_DE_BLOQUEAR_ATAQUES_BASICOS,
    bonus_ref_name: 'bloquear_ataques',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.bloquear_ataques'] },
    values: { min: 1, max: 10 },
    valid: ['escudo'],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.VELOCIDAD_DE_MOVIMIENTO,
    bonus_ref_name: 'vm',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['general.vm'] },
    values: { min: 1, max: 20 },
    valid: ['escudo'],
  },
  {
    category: { type: 'bonus6_7' },
    full_name: allFullNameBonusList.REGENERACION_DE_HP,
    bonus_ref_name: 'regen_hp',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['general.regen_hp'] },
    values: { min: 1, max: 35 },
    valid: ['pendiente'],
  },
];
