import { allFullNameBonusList, BonusType } from "netim2-shared";

export const CORRUPT_IMPLICIT_BONUS: BonusType[] = [
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_VIT,
    bonus_ref_name: 'VIT',
    effects: { type: 'attribute_modifier', operation: 'flat', target: 'atribute.VIT.bonusPoints' },
    values: {min:1,max: 1},
    valid: ['escudo', 'arma'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_MISTICOS,
    bonus_ref_name: 'misticos',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.misticos'] },
    values: {min:1,max: 2},
    valid: ['escudo', 'arma'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_STR,
    bonus_ref_name: 'STR',
    effects: { type: 'attribute_modifier', operation: 'flat', target: 'atribute.STR.bonusPoints' },
    values: {min:1,max: 1},
    valid: ['casco', 'botas'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_DEMONIOS,
    bonus_ref_name: 'demonios',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.demonios'] },
    values: {min:1,max: 2},
    valid: ['casco', 'botas'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_INT,
    bonus_ref_name: 'INT',
    effects: { type: 'attribute_modifier', operation: 'flat', target: 'atribute.INT.bonusPoints' },
    values: {min:1,max: 1},
    valid: ['armadura', 'brazalete'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_ORCOS,
    bonus_ref_name: 'orcos',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.orcos'] },
    values: {min:1,max: 2},
    valid: ['armadura', 'brazalete'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_DEX,
    bonus_ref_name: 'DEX',
    effects: { type: 'attribute_modifier', operation: 'flat', target: 'atribute.DEX.bonusPoints' },
    values: {min:1,max: 1},
    valid: ['pendiente', 'collar'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_ANIMALES,
    bonus_ref_name: 'animales',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.animales'] },
    values: {min:1,max: 2},
    valid: ['pendiente', 'collar'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_PENETRACION_HABILIDAD,
    bonus_ref_name: 'penetracion_habilidad',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.penetracion_habilidad'] },
    values: {min:1,max: 1},
    valid: ['arma'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_VA,
    bonus_ref_name: 'va',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['general.va'] },
    values: {min:1,max: 2},
    valid: ['arma'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_MEDIO_HUMANOS,
    bonus_ref_name: 'medio_humanos',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.medio_humanos'] },
    values: {min:1,max: 5},
    valid: ['casco'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_MONSTRUOS,
    bonus_ref_name: 'monstruos',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.monstruos'] },
    values: {min:1,max: 5},
    valid: ['casco'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_DAÑO_CRITICO,
    bonus_ref_name: 'daño_critico',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.daño_critico'] },
    values: {min:1,max: 5},
    valid: ['armadura'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_MAX_HP,
    bonus_ref_name: 'hp',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['general.hp'] },
    values: {min:150,max: 700},
    valid: ['armadura'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_DURACION_ESTADO,
    bonus_ref_name: 'duracion_estado',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.duracion_estado'] },
    values: {min:1,max: 4},
    valid: ['escudo'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_VM,
    bonus_ref_name: 'vm',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['general.vm'] },
    values: {min:1,max: 5},
    valid: ['escudo'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_BONUS_ESTADO,
    bonus_ref_name: 'bonus_estado',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.bonus_estado'] },
    values: {min:1,max: 2},
    valid: ['botas'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_REGEN_HP,
    bonus_ref_name: 'regen_hp',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['general.regen_hp'] },
    values: {min:5,max: 10},
    valid: ['botas'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_BONUS_VENENO,
    bonus_ref_name: 'bonus_veneno',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.bonus_veneno'] },
    values: {min:1,max: 4},
    valid: ['collar'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_VH,
    bonus_ref_name: 'vh',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['general.vh'] },
    values: {min:1,max: 1},
    valid: ['collar'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_BONUS_SANGRAD,
    bonus_ref_name: 'bonus_sangrado',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.bonus_sangrado'] },
    values: {min:1,max: 4},
    valid: ['brazalete'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_RESISTENCIA_AL_DAÑO_DE_HABILIDAD,
    bonus_ref_name: 'def_hab',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.def_hab'] },
    values: {min:1,max: 1},
    valid: ['brazalete'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_BONUS_INCENDIO,
    bonus_ref_name: 'bonus_fuego',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.bonus_fuego'] },
    values: {min:1,max: 4},
    valid: ['pendiente'],
  },
  {
    category: { type: 'corrupt', sub_type: 'corrupt_item_acc' },
    full_name: allFullNameBonusList.CORRUPT_IMPLICIT_RESISTENCIA_AL_DAÑO_DE_MEDIA,
    bonus_ref_name: 'def_media',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.def_media'] },
    values: {min:1,max: 1},
    valid: ['pendiente'],
  },
];
