import { allFullNameBonusList, BonusType } from "netim2-shared";


export const tier2BonusList: BonusType[] = [
  {
    category: { type: 'generic', tier: 2 },
    full_name: allFullNameBonusList.DEFENSA_ESPADA,
    bonus_ref_name: 'def_espada',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.defensa.def_espada'] }],
    values: { min: 5, max: 10 },
    valid: ['brazalete', 'pendiente', 'casco', 'armadura'],
  },
  {
    category: { type: 'generic', tier: 2 },
    full_name: allFullNameBonusList.DEFENSA_DOS_MANOS,
    bonus_ref_name: 'def_dos_manos',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.defensa.def_dos_manos'] }],
    values: { min: 5, max: 10 },
    valid: ['brazalete', 'pendiente', 'casco', 'armadura'],
  },
  {
    category: { type: 'generic', tier: 2 },
    full_name: allFullNameBonusList.DEFENSA_DAGA,
    bonus_ref_name: 'def_daga',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.defensa.def_daga'] }],
    values: { min: 5, max: 10 },
    valid: ['brazalete', 'pendiente', 'casco', 'armadura'],
  },
  {
    category: { type: 'generic', tier: 2 },
    full_name: allFullNameBonusList.DEFENSA_FAN,
    bonus_ref_name: 'def_fan',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.defensa.def_fan'] }],
    values: { min: 5, max: 10 },
    valid: ['brazalete', 'pendiente', 'casco', 'armadura'],
  },
  {
    category: { type: 'generic', tier: 2 },
    full_name: allFullNameBonusList.DEFENSA_CAMPANA,
    bonus_ref_name: 'def_campana',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.defensa.def_campana'] }],
    values: { min: 5, max: 10 },
    valid: ['brazalete', 'pendiente', 'casco', 'armadura'],
  },
  {
    category: { type: 'generic', tier: 2 },
    full_name: allFullNameBonusList.RESISTENCIA_A_FLECHAS,
    bonus_ref_name: 'def_flecha',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.defensa.def_flecha'] }],
    values: { min: 5, max: 10 },
    valid: ['brazalete', 'pendiente', 'casco', 'armadura'],
  },
  {
    category: { type: 'generic', tier: 2 },
    full_name: allFullNameBonusList.RESISTENCIA_MAGIA,
    bonus_ref_name: 'def_magia',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.defensa.def_magia'] }],
    values: { min: 1, max: 10 },
    valid: ['brazalete', 'pendiente', 'casco', 'armadura'],
  },
  {
    category: { type: 'generic', tier: 2 },
    full_name: allFullNameBonusList.PROB_DE_GOLPES_CRITICOS,
    bonus_ref_name: 'critico',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.daño.critico'] }],
    values: { min: 1, max: 10 },
    valid: ['arma', 'botas', 'collar'],
  },
  {
    category: { type: 'generic', tier: 2 },
    full_name: allFullNameBonusList.PROB_DE_RETARDO,
    bonus_ref_name: 'retardo',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.cc.retardo'] }],
    values: { min: 1, max: 15 },
    valid: ['arma', 'casco'],
  },
  {
    category: { type: 'generic', tier: 2 },
    full_name: allFullNameBonusList.OPCION_DE_DESMAYO,
    bonus_ref_name: 'desmayo',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.cc.desmayo'] }],
    values: { min: 1, max: 10 },
    valid: ['arma', 'collar', 'botas'],
  },
  {
    category: { type: 'generic', tier: 2 },
    full_name: allFullNameBonusList.PROB_DE_GOLPES_DE_PENETRACION,
    bonus_ref_name: 'penetracion',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.daño.penetracion'] }],
    values: { min: 1, max: 10 },
    valid: ['arma', 'brazalete', 'collar'],
  },
  {
    category: { type: 'generic', tier: 2 },
    full_name: allFullNameBonusList.PROB_DE_CAER_MAS_OBJETOS,
    bonus_ref_name: 'chances_objetos',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.miscs.chances_objetos'] }],
    values: { min: 1, max: 20 },
    valid: ['brazalete', 'pendiente', 'botas'],
  },
  {
    category: { type: 'generic', tier: 2 },
    full_name: allFullNameBonusList.AUMENTO_DE_OBJETOS_RAROS,
    bonus_ref_name: 'chances_raros',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.miscs.chances_raros'] }],
    values: { min: 1, max: 20 },
    valid: ['brazalete', 'pendiente', 'botas'],
  },
  {
    category: { type: 'generic', tier: 2 },
    full_name: allFullNameBonusList.FRECUENCIA_DE_YANG,
    bonus_ref_name: 'chances_yang',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.miscs.chances_yang'] }],
    values: { min: 1, max: 20 },
    valid: ['collar', 'escudo', 'botas'],
  },
  {
    category: { type: 'generic', tier: 2 },
    full_name: allFullNameBonusList.PROB_DE_OBTENER_BONUS_DE_EXP,
    bonus_ref_name: 'chances_exp',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.miscs.chances_exp'] }],
    values: { min: 1, max: 20 },
    valid: ['collar', 'botas', 'escudo'],
  },
  {
    category: { type: 'generic', tier: 2 },
    full_name: allFullNameBonusList.DEFENSA_CONTRA_DESMAYO,
    bonus_ref_name: 'def_desmayo',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.defensa.def_desmayo'] }],
    values: { min: 1, max: 50 },
    valid: ['escudo'],
  },
];
