import { allFullNameBonusList, BonusType } from "netim2-shared";
export const tier1BonusList: BonusType[] = [
  {
    category: { type: 'generic', tier: 1 },
    full_name: allFullNameBonusList.FUERZA_CONTRA_ORCOS,
    bonus_ref_name: 'orcos',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.orcos'] },
    values: { min: 10, max: 20 },
    valid: ['arma', 'brazalete', 'collar', 'pendiente', 'casco'],
  },
  {
    category: { type: 'generic', tier: 1 },
    full_name: allFullNameBonusList.FUERZA_CONTRA_ANIMALES,
    bonus_ref_name: 'animales',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.animales'] },
    values: { min: 10, max: 20 },
    valid: ['arma', 'brazalete', 'collar', 'pendiente', 'casco'],
  },
  {
    category: { type: 'generic', tier: 1 },
    full_name: allFullNameBonusList.FUERZA_CONTRA_MISTICOS,
    bonus_ref_name: 'misticos',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.misticos'] },
    values: { min: 10, max: 20 },
    valid: ['arma', 'brazalete', 'collar', 'pendiente', 'casco'],
  },
  {
    category: { type: 'generic', tier: 1 },
    full_name: allFullNameBonusList.FUERZA_CONTRA_DEMONIOS,
    bonus_ref_name: 'demonios',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.demonios'] },
    values: { min: 10, max: 20 },
    valid: ['arma', 'brazalete', 'collar', 'pendiente', 'casco'],
  },
  {
    category: { type: 'generic', tier: 1 },
    full_name: allFullNameBonusList.DEFENSA_CONTRA_RETARDO,
    bonus_ref_name: 'def_retardo',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.def_retardo'] },
    values: { min: 1, max: 50 },
    valid: ['escudo'],
  },
  {
    category: { type: 'generic', tier: 1 },
    full_name: allFullNameBonusList.PROB_ES_DE_REFLECTAR_GOLPES_BASICOS,
    bonus_ref_name: 'reflectar',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.reflectar'] },
    values: { min: 1, max: 25 },
    valid: ['armadura', 'escudo'],
  },
  {
    category: { type: 'generic', tier: 1 },
    full_name: allFullNameBonusList.PROB_DE_BLOQUEAR_ATAQUES_BASICOS,
    bonus_ref_name: 'bloquear_ataques',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.bloquear_ataques'] },
    values: { min: 1, max: 10 },
    valid: ['escudo', 'botas'],
  },
  {
    category: { type: 'generic', tier: 1 },
    full_name: allFullNameBonusList.RESISTENCIA_AL_FUEGO,
    bonus_ref_name: 'def_incendio',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.def_incendio'] },
    values: { min: 1, max: 10 },
    valid: ['casco', 'botas', 'armadura'],
  },
  {
    category: { type: 'generic', tier: 1 },
    full_name: allFullNameBonusList.RESISTENCIA_AL_VENENO,
    bonus_ref_name: 'def_veneno',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.def_veneno'] },
    values: { min: 1, max: 10 },
    valid: ['casco', 'botas', 'armadura'],
  },
  {
    category: { type: 'generic', tier: 1 },
    full_name: allFullNameBonusList.RESISTENCIA_AL_SANGRADO,
    bonus_ref_name: 'def_sangrado',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.def_sangrado'] },
    values: { min: 1, max: 10 },
    valid: ['casco', 'botas', 'armadura'],
  },
];
