import { allFullNameBonusList, BonusType } from "netim2-shared";


export const tier3BonusList: BonusType[] = [
  {
    category: { type: 'generic', tier: 3 },
    full_name: allFullNameBonusList.VELOCIDAD_DE_ATAQUE,
    bonus_ref_name: 'va',
    effects: [{ type: 'stat', operation: 'flat', target: ['general.va'] }],
    values: { min: 1, max: 10 },
    valid: ['botas', 'casco'],
  },
  {
    category: { type: 'generic', tier: 3 },
    full_name: allFullNameBonusList.MAX_HP,
    bonus_ref_name: 'hp',
    effects: [{ type: 'stat', operation: 'flat', target: ['general.hp'] }],
    values: { min: 100, max: 2000 },
    valid: ['brazalete', 'collar', 'armadura', 'botas'],
  },
  {
    category: { type: 'generic', tier: 3 },
    full_name: allFullNameBonusList.VALOR_DE_ATAQUE,
    bonus_ref_name: 'ad',
    effects: [{ type: 'stat', operation: 'flat', target: ['general.ad'] }],
    values: { min: 10, max: 30 },
    valid: ['armadura'],
  },
  {
    category: { type: 'generic', tier: 3 },
    full_name: allFullNameBonusList.OPCION_DE_ENVENENAMIENTO,
    bonus_ref_name: 'veneno',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.daño.veneno'] }],
    values: { min: 1, max: 15 },
    valid: ['arma', 'casco'],
  },
  {
    category: { type: 'generic', tier: 3 },
    full_name: allFullNameBonusList.STR,
    bonus_ref_name: 'STR',
    effects: [{ type: 'stat', operation: 'flat', target: [] }],
    values: { min: 2, max: 12 },
    valid: ['arma', 'pendiente', 'escudo'],
  },
  {
    category: { type: 'generic', tier: 3 },
    full_name: allFullNameBonusList.INT,
    bonus_ref_name: 'INT',
    effects: [{ type: 'stat', operation: 'flat', target: [] }],
    values: { min: 2, max: 12 },
    valid: ['arma', 'pendiente', 'escudo'],
  },
  {
    category: { type: 'generic', tier: 3 },
    full_name: allFullNameBonusList.DEX,
    bonus_ref_name: 'DEX',
    effects: [{ type: 'stat', operation: 'flat', target: [] }],
    values: { min: 2, max: 12 },
    valid: ['arma', 'pendiente', 'escudo'],
  },
  {
    category: { type: 'generic', tier: 3 },
    full_name: allFullNameBonusList.VIT,
    bonus_ref_name: 'VIT',
    effects: [{ type: 'stat', operation: 'flat', target: [] }],
    values: { min: 2, max: 12 },
    valid: ['arma', 'pendiente', 'escudo'],
  },
  {
    category: { type: 'generic', tier: 3 },
    full_name: allFullNameBonusList.FUERZA_CONTRA_MONSTRUOS,
    bonus_ref_name: 'monstruos',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.daño.monstruos'] }],
    values: { min: 5, max: 20 },
    valid: ['pendiente', 'collar', 'escudo'],
  },
  {
    category: { type: 'generic', tier: 3 },
    full_name: allFullNameBonusList.FUERZA_CONTRA_MEDIO_HUMANOS,
    bonus_ref_name: 'medio_humanos',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.daño.medio_humanos'] }],
    values: { min: 5, max: 20 },
    valid: ['escudo', 'brazalete', 'pendiente'],
  },
  {
    category: { type: 'generic', tier: 3 },
    full_name: allFullNameBonusList.DAÑO_CRITICO,
    bonus_ref_name: 'daño_critico',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.daño.daño_critico'] }],
    values: { min: 1, max: 15 },
    valid: ['casco', 'armadura', 'collar'],
  },
  {
    category: { type: 'generic', tier: 3 },
    full_name: allFullNameBonusList.CORTA_CURACION,
    bonus_ref_name: 'corta_curacion',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.defensa.corta_curacion'] }],
    values: { min: 1, max: 50 },
    valid: ['armadura', 'escudo'],
  },
  {
    category: { type: 'generic', tier: 3 },
    full_name: allFullNameBonusList.OPCION_DE_SANGRADO,
    bonus_ref_name: 'sangrado',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.daño.sangrado'] }],
    values: { min: 1, max: 15 },
    valid: ['botas', 'brazalete'],
  },
  {
    category: { type: 'generic', tier: 3 },
    full_name: allFullNameBonusList.OPCION_DE_INCENDIO,
    bonus_ref_name: 'incendio',
    effects: [{ type: 'stat', operation: 'flat', target: ['bonus.daño.incendio'] }],
    values: { min: 1, max: 15 },
    valid: ['pendiente', 'collar'],
  },
];
