import { allFullNameBonusList, BonusType } from "netim2-shared";

export const tier4BonusList: BonusType[] = [
  {
    category: { type: 'generic', tier: 4 },
    full_name: allFullNameBonusList.DAÑO_DE_MEDIA,
    bonus_ref_name: 'media',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.media'] },
    values: { min: 1, max: 60 },
    valid: ['arma'],
  },
  {
    category: { type: 'generic', tier: 4 },
    full_name: allFullNameBonusList.REGENERACION_DE_HP,
    bonus_ref_name: 'regen_hp',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['general.regen_hp'] },
    values: { min: 5, max: 50 },
    valid: ['escudo'],
  },
  {
    category: { type: 'generic', tier: 4 },
    full_name: allFullNameBonusList.PENETRACION_HABILIDAD,
    bonus_ref_name: 'penetracion_habilidad',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.penetracion_habilidad'] },
    values: { min: 1, max: 7 },
    valid: ['brazalete'],
  },
  {
    category: { type: 'generic', tier: 4 },
    full_name: allFullNameBonusList.DAÑO_DE_HABILIDAD,
    bonus_ref_name: 'habilidad',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.daño.habilidad'] },
    values: { min: 1, max: 30 },
    valid: ['arma'],
  },
  {
    category: { type: 'generic', tier: 4 },
    full_name: allFullNameBonusList.ROBO_DE_VIDA,
    bonus_ref_name: 'robo_vida',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.robo_vida'] },
    values: { min: 1, max: 3 },
    valid: ['armadura'],
  },
  {
    category: { type: 'generic', tier: 4 },
    full_name: allFullNameBonusList.RESISTENCIA_AL_DAÑO_DE_HABILIDAD,
    bonus_ref_name: 'def_hab',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.def_hab'] },
    values: { min: 1, max: 7 },
    valid: ['escudo', 'casco'],
  },
  {
    category: { type: 'generic', tier: 4 },
    full_name: allFullNameBonusList.RESISTENCIA_AL_DAÑO_DE_MEDIA,
    bonus_ref_name: 'def_media',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.def_media'] },
    values: { min: 1, max: 7 },
    valid: ['collar', 'pendiente'],
  },
  {
    category: { type: 'generic', tier: 4 },
    full_name: allFullNameBonusList.VAMPIRISMO_DE_HECHIZO,
    bonus_ref_name: 'vampirismo_hechizo',
    effects: { type: 'stat_modifiers', operation: 'flat', target: ['bonus.defensa.vampirismo_hechizo'] },
    values: { min: 1, max: 5 },
    valid: ['botas'],
  },
];
