import { EquipType, IdItem } from "netim2-shared";
import { createEquipItem } from "src/modules/item/factories/item-builder";


export const ARCO_LIST: EquipType[] = [
    createEquipItem({
        idItem: IdItem.ARCO,
        restricted: ['ninja'],
        name: "Arco",
        lvReq: 1,
        img: '/items/Arco.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'flecha',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.ARCO_LARGO,
        restricted: ['ninja'],
        name: 'Arco Largo',
        lvReq: 5,
        img: '/items/Arco_Largo.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'flecha',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.ARCO_COMPUESTO,
        restricted: ['ninja'],
        name: 'Arco Compuesto',
        lvReq: 10,
        img: '/items/Arco_Compuesto.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'flecha',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.ARCO_DE_BATALLA,
        restricted: ['ninja'],
        name: 'Arco de Batalla',
        lvReq: 15,
        img: '/items/Arco_de_Batalla.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'flecha',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.ARCO_LARGO_DE_MONTAR,
        restricted: ['ninja'],
        name: 'Arco largo de Montar',
        lvReq: 20,
        img: '/items/Arco_largo_de_Montar.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'flecha',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.ARCO_DE_BAT_DE_MONTA,
        restricted: ['ninja'],
        name: 'Arco de Bat. de Monta',
        lvReq: 25,
        img: '/items/Arco_de_Bat._de_Monta.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'flecha',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.ARCO_CUERNO,
        restricted: ['ninja'],
        name: 'Arco Cuerno',
        lvReq: 30,
        img: '/items/Arco_Cuerno.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'flecha',
        especial: true,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.ARCO_COBRE_ARTESANAL,
        restricted: ['ninja'],
        name: 'Arco Cobre Artesanal',
        lvReq: 32,
        img: '/items/Arco_Cobre_Artesanal.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'flecha',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.ARCO_RUINA_NEGRA,
        restricted: ['ninja'],
        name: 'Arco Ruina Negra',
        lvReq: 36,
        img: '/items/Arco_Ruina_Negra.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'flecha',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.ARCO_OJO_ROJO,
        restricted: ['ninja'],
        name: 'Arco Ojo Rojo',
        lvReq: 40,
        img: '/items/Arco_Ojo_Rojo.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'flecha',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.ARCO_HOJA_ESPINOSA,
        restricted: ['ninja'],
        name: 'Arco Hoja Espinosa',
        lvReq: 45,
        img: '/items/Arco_Hoja_Espinosa.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'flecha',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.ARCO_CUERNO_DE_TORO,
        restricted: ['ninja'],
        name: 'Arco Cuerno de Toro',
        lvReq: 50,
        img: '/items/Arco_Cuerno_de_Toro.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'flecha',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.ARCO_UNICORNIO,
        restricted: ['ninja'],
        name: 'Arco Unicornio',
        lvReq: 55,
        img: '/items/Arco_Unicornio.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'flecha',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.ARCO_ALA_GIGANTE,
        restricted: ['ninja'],
        name: 'Arco Ala Gigante',
        lvReq: 60,
        img: '/items/Arco_Ala_Gigante.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'flecha',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.ARCO_ALBARICOQUE_DIV,
        restricted: ['ninja'],
        name: 'Arco Albaricoque Div.',
        lvReq: 65,
        img: '/items/Arco_Albaricoque_Div.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'flecha',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.ARCO_DRAGON_AMARILLO,
        restricted: ['ninja'],
        name: 'Arco Dragón Amarillo',
        lvReq: 65,
        img: '/items/Arco_Dragón_Amarillo.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'flecha',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.ARCO_DRAGON_AZUL,
        restricted: ['ninja'],
        name: 'Arco Dragón Azul',
        lvReq: 70,
        img: '/items/Arco_Dragón_Azul.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'flecha',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.ARCO_CUERVO_DE_ACERO,
        restricted: ['ninja'],
        name: 'Arco Cuervo de Acero',
        lvReq: 75,
        img: '/items/Arco_Cuervo_de_Acero.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'flecha',
        especial: true,
        price: 300,
        slot: 3
    }),
]