import { createEquipItem } from "src/modules/item/factories/item-builder";
import { EquipType } from "src/modules/item/types/entities-props/equip.type";
import { IdItem } from "src/modules/item/types/iditems/id-item-list.type";

export const CAMPANA_LIST: EquipType[] = [
    createEquipItem({
        idItem: IdItem.CAMPANA_DE_COBRE,
        restricted: ['chaman'],
        name: 'Campana de Cobre',
        lvReq: 10,
        img: '/items/Campana_de_Cobre.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'campana',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.CAMPANA_DE_PLATA,
        restricted: ['chaman'],
        name: 'Campana de Plata',
        lvReq: 15,
        img: '/items/Campana_de_Plata.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'campana',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.CAMPANA_DORADA,
        restricted: ['chaman'],
        name: 'Campana Dorada',
        lvReq: 20,
        img: '/items/Campana_Dorada.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'campana',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.CAMPANA_ANTIGUA,
        restricted: ['chaman'],
        name: 'Campana Antigua',
        lvReq: 30,
        img: '/items/Campana_antigua.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'campana',
        especial: true,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.CAMPANA_DE_JADE,
        restricted: ['chaman'],
        name: 'Campana de Jade',
        lvReq: 32,
        img: '/items/Campana_de_Jade.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'campana',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.CAMPANA_FUENTE,
        restricted: ['chaman'],
        name: 'Campana Fuente',
        lvReq: 36,
        img: '/items/Campana_Fuente.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'campana',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.CAMPANA_ALBARICOQUE,
        restricted: ['chaman'],
        name: 'Campana Albaricoque',
        lvReq: 40,
        img: '/items/Campana_albaricoque.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'campana',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.CAMPANA_MAGICA,
        restricted: ['chaman'],
        name: 'Campana Mágica',
        lvReq: 50,
        img: '/items/Campana_magica.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'campana',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.CAMPANA_INSECTO_DORADO,
        restricted: ['chaman'],
        name: 'Campana Insecto Dorado',
        lvReq: 55,
        img: '/items/Campana_Insecto_Dorado.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'campana',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.CAMPANA_INSECTO_ACERO,
        restricted: ['chaman'],
        name: 'Campana Insecto Acero',
        lvReq: 60,
        img: '/items/Campana_Insecto_Acero.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'campana',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.CAMPANA_PAJARO_TRUENO,
        restricted: ['chaman'],
        name: 'Campana Pájaro Trueno',
        lvReq: 65,
        img: '/items/Campana_pajaro_trueno.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'campana',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.CAMPANA_CIELO_Y_TIERRA,
        restricted: ['chaman'],
        name: 'Campana Cielo y Tierra',
        lvReq: 65,
        img: '/items/Campana_cielo_y_tierra.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'campana',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.CAMPANA_BAMBU,
        restricted: ['chaman'],
        name: 'Campana Bambú',
        lvReq: 75,
        img: '/items/Campana_Bambú.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'campana',
        especial: true,
        price: 300,
        slot: 3
    }),
]