import { EquipType, IdItem } from "netim2-shared";
import { createEquipItem } from "src/modules/item/factories/item-builder";


export const DAGA_LIST: EquipType[] = [
    createEquipItem({
        idItem: IdItem.DAGA,
        restricted: ['ninja'],
        name: "Daga",
        lvReq: 1,
        img: '/items/Daga.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'daga',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.AMIJA,
        restricted: ['ninja'],
        name: 'Amija',
        lvReq: 5,
        img: '/items/Amija.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'daga',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.DAGA_COBRA,
        restricted: ['ninja'],
        name: 'Daga Cobra',
        lvReq: 10,
        img: '/items/Daga_Cobra.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'daga',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.NUEVE_HOJAS,
        restricted: ['ninja'],
        name: 'Nueve Hojas',
        lvReq: 15,
        img: '/items/Nueve_Hojas.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'daga',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.DAGA_TIJERA,
        restricted: ['ninja'],
        name: 'Daga Tijera',
        lvReq: 20,
        img: '/items/Daga_Tijera.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'daga',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.CUCHILLO_CORTO,
        restricted: ['ninja'],
        name: 'Cuchillo Corto',
        lvReq: 25,
        img: '/items/Cuchillo_Corto.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'daga',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.DIRK_HOJA_NEGRA,
        restricted: ['ninja'],
        name: 'Dirk Hoja Negra',
        lvReq: 30,
        img: '/items/Dirk_Hoja_Negra.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'daga',
        especial: true,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.DAGA_AFORTUNADA,
        restricted: ['ninja'],
        name: 'Daga Afortunada',
        lvReq: 32,
        img: '/items/Daga_Afortunada.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'daga',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.DAGA_MORDISCO_DE_GATO,
        restricted: ['ninja'],
        name: 'Daga Mordisco de Gato',
        lvReq: 36,
        img: '/items/Daga_Mordisco_de_Gato.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'daga',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.DAGA_MASCARA_DIABLO,
        restricted: ['ninja'],
        name: 'Daga Máscara Diablo',
        lvReq: 40,
        img: '/items/Daga_Máscara_Diablo.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'daga',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.DAGA_PUNO_DIABLO,
        restricted: ['ninja'],
        name: 'Daga Puño Diablo',
        lvReq: 45,
        img: '/items/Daga_Puño_Diablo.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'daga',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.DAGA_SANGRIENTA,
        restricted: ['ninja'],
        name: 'Daga Sangrienta',
        lvReq: 50,
        img: '/items/Daga_Sangrienta.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'daga',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.DAGA_COSTILLA,
        restricted: ['ninja'],
        name: 'Daga Costilla',
        lvReq: 55,
        img: '/items/Daga_Costilla.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'daga',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.CHAKRAM,
        restricted: ['ninja'],
        name: 'Chakram',
        lvReq: 60,
        img: '/items/Chakram.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'daga',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.DAGA_RELAMPAGO,
        restricted: ['ninja'],
        name: 'Daga Relámpago',
        lvReq: 65,
        img: '/items/Daga_Relámpago.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'daga',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.DAGA_DRAGON,
        restricted: ['ninja'],
        name: 'Daga Dragón',
        lvReq: 65,
        img: '/items/Daga_Dragón.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'daga',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.DAGA_SIAMESA,
        restricted: ['ninja'],
        name: 'Daga Siamesa',
        lvReq: 70,
        img: '/items/Daga_Siamesa.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'daga',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.CHAKRAM_ALA_DEMONIO,
        restricted: ['ninja'],
        name: 'Chakram Ala Demonio',
        lvReq: 75,
        img: '/items/Chakram_Ala_Demonio.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'daga',
        especial: true,
        price: 300,
        slot: 3
    }),
]