import { createEquipItem } from "src/modules/item/factories/item-builder";
import { EquipType } from "src/modules/item/types/entities-props/equip.type";
import { IdItem } from "src/modules/item/types/iditems/id-item-list.type";

export const DOS_MANOS_LIST: EquipType[] = [
    createEquipItem({
        idItem: IdItem.GLAIVE,
        restricted: ['guerrero'],
        name: "Glaive",
        lvReq: 1,
        img: '/items/Icono_Glaive.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.LANZA,
        restricted: ['guerrero'],
        name: "Lanza",
        lvReq: 5,
        img: '/items/Icono_Lanza.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.GUILLOTINA,
        restricted: ['guerrero'],
        name: 'Guillotina',
        lvReq: 10,
        img: '/items/Icono_Guillotina.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.LANZA_ARANA,
        restricted: ['guerrero'],
        name: 'Lanza Araña',
        lvReq: 15,
        img: '/items/Icono_Lanza_Araña.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.GISAME,
        restricted: ['guerrero'],
        name: 'Gisame',
        lvReq: 20,
        img: '/items/Icono_Gisame.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.GISAME,
        restricted: ['guerrero'],
        name: 'Gisame',
        lvReq: 20,
        img: '/items/Icono_Gisame.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.GUADANA_DE_GUERRA,
        restricted: ['guerrero'],
        name: 'Guadaña de Guerra',
        lvReq: 25,
        img: '/items/Icono_Guadaña_Guerrera.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.HIERRO_ROJO,
        restricted: ['guerrero'],
        name: 'Hierro Rojo',
        lvReq: 30,
        img: '/items/Icono_Hierro_Rojo.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: true,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.HORCA_DE_BATALLA,
        restricted: ['guerrero'],
        name: 'Horca de Batalla',
        lvReq: 32,
        img: '/items/Icono_Horca_de_Batalla.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.HALBERD,
        restricted: ['guerrero'],
        name: 'Halberd',
        lvReq: 36,
        img: '/items/Icono_Halberd.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.HACHA_GIGANTE,
        restricted: ['guerrero'],
        name: 'Hacha Gigante',
        lvReq: 40,
        img: '/items/Icono_Hacha_Gigante.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.PICO_GLACIAR,
        restricted: ['guerrero'],
        name: 'Pico Glaciar',
        lvReq: 45,
        img: '/items/Icono_Pico_Glaciar.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_DOCE_ESPIRITUS,
        restricted: ['guerrero'],
        name: 'Espada Doce Espíritus',
        lvReq: 50,
        img: '/items/Icono_Espada_Doce_Espíritus.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.HOJA_SALVACION,
        restricted: ['guerrero'],
        name: 'Hoja Salvación',
        lvReq: 55,
        img: '/items/Icono_Espada_Salvación.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.LEON_ASESINO,
        restricted: ['guerrero'],
        name: 'León Asesino',
        lvReq: 60,
        img: '/items/Icono_León_Asesino.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_ELECTROMAGNETICA,
        restricted: ['guerrero'],
        name: 'Espada Electromagnética',
        lvReq: 65,
        img: '/items/Icono_Espada_Electromagnética.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.PARTIDARIO,
        restricted: ['guerrero'],
        name: 'Partidario',
        lvReq: 65,
        img: '/items/Icono_Partidario.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.HOJA_ROBA_ALMAS,
        restricted: ['guerrero'],
        name: 'Hoja Roba Almas',
        lvReq: 70,
        img: '/items/Icono_Espada_Roba_Almas.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: false,
        price: 300,
        slot: 3
    }),
        createEquipItem({
        idItem: IdItem.ESPADA_RESENTIMIENTO,
        restricted: ['guerrero'],
        name: 'Espada Resentimiento',
        lvReq: 75,
        img: '/items/Icono_Espada_Resentimiento.png',
        size: { rows: 3, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'dos_manos',
        especial: true,
        price: 300,
        slot: 3
    }),
]