import { EquipType } from "../../../types/entities-props/equip.type";
import { IdItem } from "../../../types/iditems/id-item-list.type";
import { createEquipItem } from "src/modules/item/factories/item-builder";

export const ESPADA_LIST: EquipType[] = [
    createEquipItem({
        idItem: IdItem.ESPADA,
        restricted: ['guerrero', 'ninja', 'sura'],
        name: "Espada",
        lvReq: 1,
        img: '/items/Icono_Espada.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_LARGA,
        restricted: ['guerrero', 'ninja', 'sura'],
        name: 'Espada Larga',
        lvReq: 5,
        img: '/items/Icono_Espada_Larga.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_CRECIENTE,
        restricted: ['guerrero', 'ninja', 'sura'],
        name: "Espada Creciente",
        lvReq: 10,
        img: '/items/Icono_Espada_Creciente.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_DE_BAMBU,
        restricted: ['guerrero', 'ninja', 'sura'],
        name: 'Espada de Bambú',
        lvReq: 15,
        img: '/items/Espada_de_Bambú.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_ANCHA,
        restricted: ['guerrero', 'ninja', 'sura'],
        name: 'Espada Ancha',
        lvReq: 20,
        img: '/items/Icono_Espada_Ancha.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_DE_PLATA,
        restricted: ['guerrero', 'ninja', 'sura'],
        name: 'Espada de Plata',
        lvReq: 25,
        img: '/items/Icono_Espada_de_Plata.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_LUNA_LLENA,
        restricted: ['guerrero', 'ninja', 'sura'],
        name: 'Espada Luna LLena',
        lvReq: 30,
        img: '/items/Icono_Espada_Luna_Llena.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: true,
        price: 300,
        slot: 2,
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_ORQUIDEA,
        restricted: ['guerrero', 'ninja', 'sura'],
        name: 'Espada Orquídea',
        lvReq: 32,
        img: '/items/Icono_Espada_Orquídea.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 2,
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_BASTARDA,
        restricted: ['guerrero', 'ninja', 'sura'],
        name: 'Espada Bastarda',
        lvReq: 36,
        img: '/items/Icono_Espada_Bastarda.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 2,
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_BARBARA,
        restricted: ['guerrero', 'ninja', 'sura'],
        name: 'Espada Bárbara',
        lvReq: 40,
        img: '/items/Icono_Espada_Bárbara.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 3,
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_SANGRIENTA,
        restricted: ['guerrero', 'ninja', 'sura'],
        name: 'Espada Sangrienta',
        lvReq: 45,
        img: '/items/Icono_Espada_Sangrienta.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 3,
    }),
    createEquipItem({
        idItem: IdItem.GRAN_ESPADA,
        restricted: ['guerrero', 'ninja', 'sura'],
        name: 'Gran Espada',
        lvReq: 50,
        img: '/items/Icono_Gran_Espada.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 3,
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_BRUJO_VOLADOR,
        restricted: ['guerrero', 'ninja', 'sura'],
        name: 'Espada Brujo Volador',
        lvReq: 55,
        img: '/items/Icono_Espada_Brujo_Volador.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 3,
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_MEDIA_LUNA,
        restricted: ['guerrero', 'ninja', 'sura'],
        name: 'Espada Media Luna',
        lvReq: 60,
        img: '/items/Icono_Espada_Media_Luna.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 3,
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_NINFA,
        restricted: ['guerrero', 'ninja', 'sura'],
        name: 'Espada Ninfa',
        lvReq: 65,
        img: '/items/Icono_Espada_Ninfa.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 3,
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_DE_BATALLA,
        restricted: ['guerrero', 'ninja', 'sura'],
        name: 'Espada de Batalla',
        lvReq: 65,
        img: '/items/Icono_Espada_de_Batalla.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 3,
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_PICADURA,
        restricted: ['guerrero', 'ninja', 'sura'],
        name: 'Espada Picadura',
        lvReq: 70,
        img: '/items/Icono_Espada_Picadura.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 3,
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_ENVENENADA,
        restricted: ['guerrero', 'ninja', 'sura'],
        name: 'Espada Envenenada',
        lvReq: 75,
        img: '/items/Icono_Espada_Envenenada.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: true,
        price: 300,
        slot: 3,
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_EXORCISMO,
        restricted: ['sura'],
        name: 'Espada Exorcismo',
        lvReq: 65,
        img: '/items/Icono_Espada_Exorcismo.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 3,
    }),
    createEquipItem({
        idItem: IdItem.HOJA_COLMILLO_FANTASMA,
        restricted: ['sura'],
        name: 'Hoja Colmillo Fantasma',
        lvReq: 65,
        img: '/items/Icono_Espada_Colmillo.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 3,
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_DEMONIO,
        restricted: ['sura'],
        name: 'Espada Demonio',
        lvReq: 70,
        img: '/items/Icono_Espada_demonio.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: false,
        price: 300,
        slot: 3,
    }),
    createEquipItem({
        idItem: IdItem.ESPADA_LEON,
        restricted: ['sura'],
        name: 'Espada Demonio',
        lvReq: 75,
        img: '/items/Icono_Espada_León.png',
        size: { rows: 2, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'espada',
        especial: true,
        price: 300,
        slot: 3,
    }),

] 