import { EquipType, IdItem } from "netim2-shared";
import { createEquipItem } from "src/modules/item/factories/item-builder";


export const FAN_LIST: EquipType[] = [
    createEquipItem({
        idItem: IdItem.FAN,
        restricted: ['chaman'],
        name: 'Fan',
        lvReq: 1,
        img: '/items/Fan.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'fan',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.FAN_DE_HIERRO,
        restricted: ['chaman'],
        name: 'Fan de Hierro',
        lvReq: 5,
        img: '/items/Fan_de_Hierro.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'fan',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.FAN_TIGRE_NEGRO,
        restricted: ['chaman'],
        name: 'Fan Tigre Negro',
        lvReq: 10,
        img: '/items/Fan_Tigre_Negro.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'fan',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.FAN_ALA_GRULLA,
        restricted: ['chaman'],
        name: 'Fan ala Grulla',
        lvReq: 15,
        img: '/items/Fan_ala_Grulla.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'fan',
        especial: false,
        price: 300,
        slot: 1
    }),
    createEquipItem({
        idItem: IdItem.FAN_PAVO_REAL,
        restricted: ['chaman'],
        name: 'Fan Pavo Real',
        lvReq: 20,
        img: '/items/Fan_Pavo_Real.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'fan',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.FAN_ACUATICO,
        restricted: ['chaman'],
        name: 'Fan Acuático',
        lvReq: 25,
        img: '/items/Fan_Acuático.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'fan',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.FAN_OTONO,
        restricted: ['chaman'],
        name: 'Fan Otoño',
        lvReq: 30,
        img: '/items/Fan_otoño.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'fan',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.FAN_DE_PIEDRA,
        restricted: ['chaman'],
        name: 'Fan de Piedra',
        lvReq: 32,
        img: '/items/Fan_de_Piedra.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'fan',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.FAN_OCEANO,
        restricted: ['chaman'],
        name: 'Fan Océano',
        lvReq: 36,
        img: '/items/Fan_oceano.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'fan',
        especial: false,
        price: 300,
        slot: 2
    }),
    createEquipItem({
        idItem: IdItem.FAN_PICADURA,
        restricted: ['chaman'],
        name: 'Fan Picadura',
        lvReq: 40,
        img: '/items/Fan_Picadura.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'fan',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.FAN_FENIX,
        restricted: ['chaman'],
        name: 'Fan Fénix',
        lvReq: 45,
        img: '/items/Fan_fenix.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'fan',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.TRIPLE_FAN,
        restricted: ['chaman'],
        name: 'Triple Fan',
        lvReq: 50,
        img: '/items/Triple_Fan.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'fan',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.FAN_CEJA,
        restricted: ['chaman'],
        name: 'Fan Ceja',
        lvReq: 55,
        img: '/items/Fan_ceja.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'fan',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.FAN_SOL,
        restricted: ['chaman'],
        name: 'Fan Sol',
        lvReq: 60,
        img: '/items/Fan_sol.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'fan',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.FAN_SALVACION,
        restricted: ['chaman'],
        name: 'Fan Salvación',
        lvReq: 65,
        img: '/items/Fan_salvación.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'fan',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.FAN_PAJARO_DIVINO,
        restricted: ['chaman'],
        name: 'Fan Pájaro Divino',
        lvReq: 65,
        img: '/items/Fan_Pájaro_Divino.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'fan',
        especial: false,
        price: 300,
        slot: 3
    }),
    createEquipItem({
        idItem: IdItem.FAN_EXTASIS,
        restricted: ['chaman'],
        name: 'Fan Éxtasis',
        lvReq: 70,
        img: '/items/Fan_Éxtasis.png',
        size: { rows: 1, cols: 1 },
        sub_type_equip: 'arma',
        type_weapon: 'fan',
        especial: false,
        price: 300,
        slot: 3
    }),
]