import { IdItem, MonturaDescription } from "netim2-shared";
import { EXP_MONTURA_X_LV, MONTURA_RULES } from "src/modules/item/config/montura.config";


export const MONTURAS_LIST: MonturaDescription[] = [
    {
        name: 'Caballo',
        implicitBonus: [],
        exp: 0,
        hp: { actual: 80, max: 80 },
        idItemRef: IdItem.LICENCIA_DE_CABALLO,
        img: '/monturas/Caballo.png',
        lastUpdate: Date.now(),
        lv: 1,
        maxLv: MONTURA_RULES.low_montura_max_lv,
        nextExpLv: EXP_MONTURA_X_LV[1],
        statusIcon: '',
        idItemFood: IdItem.HENO,
        idItemRevive: IdItem.HIERBA_DEL_MONO_FACIL,
    },
    {
        name: 'Caballo Armado',
        implicitBonus: [],
        exp: 0,
        hp: { actual: 100, max: 100 },
        idItemRef: IdItem.LICENCIA_DE_CABALLO_ARMADO,
        img: '/monturas/Caballo_Armado.png',
        lastUpdate: Date.now(),
        lv: 1,
        maxLv: MONTURA_RULES.medium_montura_max_lv,
        nextExpLv: EXP_MONTURA_X_LV[1],
        statusIcon: '',
        idItemFood: IdItem.ZANAHORIA,
        idItemRevive: IdItem.HIERBA_DEL_MONO_NORMAL,
    },
    {
        name: 'Caballo Militar',
        implicitBonus: [],
        exp: 0,
        hp: { actual: 120, max: 120 },
        idItemRef: IdItem.LICENCIA_DE_CABALLO_MILITAR,
        img: '/monturas/Caballo_militar.png',
        lastUpdate: Date.now(),
        lv: 1,
        maxLv: MONTURA_RULES.high_montura_max_lv,
        nextExpLv: EXP_MONTURA_X_LV[1],
        statusIcon: '',
        idItemFood: IdItem.GINSENG_ROJO,
        idItemRevive: IdItem.HIERBA_DEL_MONO_DIFICIL,
    },
    {
        name: 'Caballo Fantasma',
        implicitBonus: [],
        exp: 0,
        hp: { actual: 120, max: 120 },
        idItemRef: IdItem.SELLO_DE_CABALLO_FANTASMA,
        img: '/monturas/Caballo_Fantasma.png',
        lastUpdate: Date.now(),
        lv: 1,
        maxLv: MONTURA_RULES.special_montura_max_lv,
        nextExpLv: 0,
        statusIcon: '',
        idItemRevive: IdItem.HIERBA_DEL_MONO_CORRUPTO,
    }
]