import { CharacterStats } from "../../types/baseCharacterProps/character-stats.type";

export const GENERAL_CHARACTER_STATS: CharacterStats = {
    general: {
        VIT: {lvPoints:0,bonusPoints:0},
        DEX: {lvPoints:0,bonusPoints:0},
        INT: {lvPoints:0,bonusPoints:0},
        STR: {lvPoints:0,bonusPoints:0},
        ad: {min:0, max: 0},
        ap: {min:0, max: 0},
        def: 0,
        hp: {actual:1000, max: 1000},
        regen_hp: 1,
        va: 0,
        vh: 0,
        vm: 0
    },
    bonus: {
        daño: {
            animales: 0,
            chaman: 0,
            critico: 0,
            demonios: 0,
            bonus_estado: 0,
            bonus_fuego: 0,
            bonus_veneno: 0,
            daño_critico: 0,
            penetracion_habilidad: 0,
            doble_golpe: 0,
            guerrero: 0,
            habilidad: 0,
            bonus_sangrado: 0,
            duracion_estado: 0,
            sangrado: 0,
            incendio: 0,
            media: 0,
            medio_humanos: 0,
            misticos: 0,
            monstruos: 0,
            ninja: 0,
            orcos: 0,
            penetracion: 0,
            sura: 0,
            veneno: 0
        },
        defensa: {
            bloquear_ataques: 0,
            campana: 0,
            daga: 0,
            damage_taken: 0,
            daño_absorbido_hp: 0,
            def_desmayo: 0,
            def_hab: 0,
            def_incendio: 0,
            corta_curacion: 0,
            def_sangrado: 0,
            def_media: 0,
            def_retardo: 0,
            def_chaman: 0,
            def_guerrero: 0,
            def_ninja: 0,
            def_sura: 0,
            def_veneno: 0,
            dos_manos: 0,
            espada: 0,
            esquivar_ataques: 0,
            esquivar_flecha: 0,
            fan: 0,
            flecha: 0,
            magia: 0,
            reflectar: 0,
        },
        cc: {
            desmayo: 0,
            retardo: 0
        },
        miscs: {
            chances_exp: 0,
            chances_objetos: 0,
            chances_raros: 0,
            chances_yang: 0,
            bonus_exp: 0,
            bonus_yang: 0,
            time_reduction: 0,
        }
    },
    fight: {
        ad_ataque_basico: 0,
        ad_mitigado: 0,
        ad_realizado: 0,
        ap_mitigado: 0,
        curacion_cortada: 0,
        sangrado_aplicado: 0,
        sangrado_realizado: 0,
        ap_realizado: 0,
        ataque_anulado: 0,
        ataque_basico_realizado: 0,
        ataque_bloqueado: 0,
        ataque_esquivado: 0,
        critico_realizado: 0,
        doble_golpe_realizado: 0,
        flecha_esquivado: 0,
        skills_used: [],
        incendio_aplicado: 0,
        incendio_realizado: 0,
        penetracion_realizado: 0,
        reflejo_aplicado: 0,
        reflejo_realizado: 0,
        retardo_aplicado: 0,
        turno_anulado: 0,
        veneno_aplicado: 0,
        veneno_realizado: 0,
        vida_curada: 0,
    }
}