import { createBuffItem } from "src/modules/item/factories/item-builder";
import { BuffType } from "src/modules/item/types/entities-props/buff.type";
import { IdItem } from "src/modules/item/types/iditems/id-item-list.type";

export const BUFF_LIST: BuffType[] = [
    createBuffItem({
        name: 'Lucioperca (Común)',
        img: '/itemsUtility/peces/Lucioperca_Común.png',
        cantidad: 1,
        lvUtility:1,
        maxCantidad: 50,
        idBuff: 4,
        description: 'Aumenta tu VIT en 3 puntos.',
        duration: 15,
        iconBuff: '/iconos/atributos_icon.png',
        effect: [{ bonusRef: 'VIT', bonusValue: 3 }],
        price: 1000,
        idItem: IdItem.LUCIOPERCA_COMUN,
    }),

    createBuffItem({
        name: 'Lucioperca (Inusual)',
        img: '/itemsUtility/peces/Lucioperca_Inusual.png',
        cantidad: 1,
        lvUtility:1,
        maxCantidad: 50,
        idBuff: 4,
        description: 'Aumenta tu VIT en 6 puntos.',
        duration: 30,
        iconBuff: '/iconos/atributos_icon.png',
        effect: [{ bonusRef: 'VIT', bonusValue: 6 }],
        price: 2000,
        idItem: IdItem.LUCIOPERCA_INUSUAL,
    }),

    createBuffItem({
        name: 'Lucioperca (Raro)',
        img: '/itemsUtility/peces/Lucioperca_Raro.png',
        cantidad: 1,
        lvUtility:1,
        maxCantidad: 50,
        idBuff: 4,
        description: 'Aumenta tu VIT en 12 puntos.',
        duration: 60,
        iconBuff: '/iconos/atributos_icon.png',
        effect: [{ bonusRef: 'VIT', bonusValue: 12 }],
        price: 5000,
        idItem: IdItem.LUCIOPERCA_RARO,
    }),

    createBuffItem({
        name: 'Pez mandarín (Común)',
        img: '/itemsUtility/peces/Pez_mandarín_Común.png',
        cantidad: 1,
        lvUtility:1,
        maxCantidad: 50,
        idBuff: 5,
        description: 'Aumenta tu DEX en 3 puntos.',
        duration: 15,
        iconBuff: '/iconos/atributos_icon.png',
        effect: [{ bonusRef: 'DEX', bonusValue: 3 }],
        price: 1000,
        idItem: IdItem.PEZ_MANDARIN_COMUN,
    }),

    createBuffItem({
        name: 'Pez mandarín (Inusual)',
        img: '/itemsUtility/peces/Pez_mandarín_Inusual.png',
        cantidad: 1,
        lvUtility:1,
        maxCantidad: 50,
        idBuff: 5,
        description: 'Aumenta tu DEX en 6 puntos.',
        duration: 30,
        iconBuff: '/iconos/atributos_icon.png',
        effect: [{ bonusRef: 'DEX', bonusValue: 6 }],
        price: 2000,
        idItem: IdItem.PEZ_MANDARIN_INUSUAL,
    }),

    createBuffItem({
        name: 'Pez mandarín (Raro)',
        img: '/itemsUtility/peces/Pez_mandarín_Raro.png',
        cantidad: 1,
        lvUtility:1,
        maxCantidad: 50,
        idBuff: 5,
        description: 'Aumenta tu DEX en 12 puntos.',
        duration: 60,
        iconBuff: '/iconos/atributos_icon.png',
        effect: [{ bonusRef: 'DEX', bonusValue: 12 }],
        price: 5000,
        idItem: IdItem.PEZ_MANDARIN_RARO,
    }),

    createBuffItem({
        name: 'Lucioperca grande (Común)',
        img: '/itemsUtility/peces/Lucioperca_grande_Común.png',
        cantidad: 1,
        lvUtility:1,
        maxCantidad: 50,
        idBuff: 6,
        description: 'Aumenta tu INT en 3 puntos.',
        duration: 15,
        iconBuff: '/iconos/atributos_icon.png',
        effect: [{ bonusRef: 'INT', bonusValue: 3 }],
        price: 1000,
        idItem: IdItem.LUCIOPERCA_GRANDE_COMUN,
    }),

    createBuffItem({
        name: 'Lucioperca grande (Inusual)',
        img: '/itemsUtility/peces/Lucioperca_grande_Inusual.png',
        cantidad: 1,
        lvUtility:1,
        maxCantidad: 50,
        idBuff: 6,
        description: 'Aumenta tu INT en 6 puntos.',
        duration: 30,
        iconBuff: '/iconos/atributos_icon.png',
        effect: [{ bonusRef: 'INT', bonusValue: 6 }],
        price: 2000,
        idItem: IdItem.LUCIOPERCA_GRANDE_INUSUAL,
    }),

    createBuffItem({
        name: 'Lucioperca grande (Raro)',
        img: '/itemsUtility/peces/Lucioperca_grande_Raro.png',
        cantidad: 1,
        lvUtility:1,
        maxCantidad: 50,
        idBuff: 6,
        description: 'Aumenta tu INT en 12 puntos.',
        duration: 60,
        iconBuff: '/iconos/atributos_icon.png',
        effect: [{ bonusRef: 'INT', bonusValue: 12 }],
        price: 5000,
        idItem: IdItem.LUCIOPERCA_GRANDE_RARO,
    }),
    createBuffItem({
        name: 'Carpa (Común)',
        img: '/itemsUtility/peces/Carpa_Común.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 7,
        description: 'Aumenta tu STR en 3 puntos.',
        duration: 15,
        iconBuff: '/iconos/atributos_icon.png',

        effect: [{ bonusRef: 'STR', bonusValue: 3 }],
        price: 1000,
        idItem: IdItem.CARPA_COMUN,
    }),

    createBuffItem({
        name: 'Carpa (Inusual)',
        img: '/itemsUtility/peces/Carpa_Inusual.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 7,
        description: 'Aumenta tu STR en 6 puntos.',
        duration: 30,
        iconBuff: '/iconos/atributos_icon.png',

        effect: [{ bonusRef: 'STR', bonusValue: 6 }],
        price: 2000,
        idItem: IdItem.CARPA_INUSUAL,
    }),

    createBuffItem({
        name: 'Carpa (Raro)',
        img: '/itemsUtility/peces/Carpa_Raro.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 7,
        description: 'Aumenta tu STR en 12 puntos.',
        duration: 60,
        iconBuff: '/iconos/atributos_icon.png',

        effect: [{ bonusRef: 'STR', bonusValue: 12 }],
        price: 5000,
        idItem: IdItem.CARPA_RARO,
    }),

    createBuffItem({
        name: 'Salmón (Común)',
        img: '/itemsUtility/peces/Salmón_Común.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 8,
        description: 'Aumenta tu AD en 10 puntos.',
        duration: 15,
        iconBuff: '/iconos/Icono-daño.png',

        effect: [{ bonusRef: 'ad', bonusValue: 10 }],
        price: 1000,
        idItem: IdItem.SALMON_COMUN,
    }),

    createBuffItem({
        name: 'Salmón (Inusual)',
        img: '/itemsUtility/peces/Salmón_Inusual.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 8,
        description: 'Aumenta tu AD en 20 puntos.',
        duration: 30,
        iconBuff: '/iconos/Icono-daño.png',

        effect: [{ bonusRef: 'ad', bonusValue: 20 }],
        price: 2000,
        idItem: IdItem.SALMON_INUSUAL,
    }),

    createBuffItem({
        name: 'Salmón (Raro)',
        img: '/itemsUtility/peces/Salmón_Raro.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 8,
        description: 'Aumenta tu AD en 40 puntos.',
        duration: 60,
        iconBuff: '/iconos/Icono-daño.png',

        effect: [{ bonusRef: 'ad', bonusValue: 40 }],
        price: 5000,
        idItem: IdItem.SALMON_RARO,
    }),

    createBuffItem({
        name: 'Carpa herbívora (Común)',
        img: '/itemsUtility/peces/Carpa_herbívora_Común.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 9,
        description: 'Aumenta tu AP en 10 puntos.',
        duration: 15,
        iconBuff: '/iconos/Icono-daño.png',

        effect: [{ bonusRef: 'ap', bonusValue: 10 }],
        price: 1000,
        idItem: IdItem.CARPA_HERBIVORA_COMUN,
    }),

    createBuffItem({
        name: 'Carpa herbívora (Inusual)',
        img: '/itemsUtility/peces/Carpa_herbívora_Inusual.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 9,
        description: 'Aumenta tu AP en 20 puntos.',
        duration: 30,
        iconBuff: '/iconos/Icono-daño.png',

        effect: [{ bonusRef: 'ap', bonusValue: 20 }],
        price: 2000,
        idItem: IdItem.CARPA_HERBIVORA_INUSUAL,
    }),

    createBuffItem({
        name: 'Carpa herbívora (Raro)',
        img: '/itemsUtility/peces/Carpa_herbívora_Raro.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 9,
        description: 'Aumenta tu AP en 40 puntos.',
        duration: 60,
        iconBuff: '/iconos/Icono-daño.png',

        effect: [{ bonusRef: 'ap', bonusValue: 40 }],
        price: 5000,
        idItem: IdItem.CARPA_HERBIVORA_RARO,
    }),

    createBuffItem({
        name: 'Trucha de arroyo (Común)',
        img: '/itemsUtility/peces/Trucha_de_arroyo_Común.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 10,
        description: 'Aumenta tu Velocidad de Movimiento en 10 puntos.',
        duration: 15,
        iconBuff: '/iconos/vm_Icon.png',

        effect: [{ bonusRef: 'vm', bonusValue: 10 }],
        price: 1000,
        idItem: IdItem.TRUCHA_DE_ARROYO_COMUN,
    }),

    createBuffItem({
        name: 'Trucha de arroyo (Inusual)',
        img: '/itemsUtility/peces/Trucha_de_arroyo_Inusual.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 10,
        description: 'Aumenta tu Velocidad de Movimiento en 20 puntos.',
        duration: 30,
        iconBuff: '/iconos/vm_Icon.png',

        effect: [{ bonusRef: 'vm', bonusValue: 20 }],
        price: 2000,
        idItem: IdItem.TRUCHA_DE_ARROYO_INUSUAL,
    }),

    createBuffItem({
        name: 'Trucha de arroyo (Raro)',
        img: '/itemsUtility/peces/Trucha_de_arroyo_Raro.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 10,
        description: 'Aumenta tu Velocidad de Movimiento en 40 puntos.',
        duration: 60,
        iconBuff: '/iconos/vm_Icon.png',

        effect: [{ bonusRef: 'vm', bonusValue: 40 }],
        price: 5000,
        idItem: IdItem.TRUCHA_DE_ARROYO_RARO,
    }),

    createBuffItem({
        name: 'Anguila (Común)',
        img: '/itemsUtility/peces/Anguila_Común.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 11,
        description: 'Aumenta tu Velocidad de Ataque en 5 puntos.',
        duration: 15,
        iconBuff: '/iconos/va_Icon.png',

        effect: [{ bonusRef: 'va', bonusValue: 5 }],
        price: 1000,
        idItem: IdItem.ANGUILA_COMUN,
    }),

    createBuffItem({
        name: 'Anguila (Inusual)',
        img: '/itemsUtility/peces/Anguila_Inusual.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 11,
        description: 'Aumenta tu Velocidad de Ataque en 7 puntos.',
        duration: 30,
        iconBuff: '/iconos/va_Icon.png',

        effect: [{ bonusRef: 'va', bonusValue: 7 }],
        price: 2000,
        idItem: IdItem.ANGUILA_INUSUAL,
    }),

    createBuffItem({
        name: 'Anguila (Raro)',
        img: '/itemsUtility/peces/Anguila_Raro.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 11,
        description: 'Aumenta tu Velocidad de Ataque en 10 puntos.',
        duration: 60,
        iconBuff: '/iconos/va_Icon.png',

        effect: [{ bonusRef: 'va', bonusValue: 10 }],
        price: 5000,
        idItem: IdItem.ANGUILA_RARO,
    }),

    createBuffItem({
        name: 'Trucha arcoíris (Común)',
        img: '/itemsUtility/peces/Trucha_arcoíris_Común.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 12,
        description: 'Aumenta tu Velocidad de Hechizo en 10 puntos.',
        duration: 15,
        iconBuff: '/iconos/Icono-Prisa.png',

        effect: [{ bonusRef: 'vh', bonusValue: 10 }],
        price: 1000,
        idItem: IdItem.TRUCHA_ARCOIRIS_COMUN,
    }),

    createBuffItem({
        name: 'Trucha arcoíris (Inusual)',
        img: '/itemsUtility/peces/Trucha_arcoíris_Inusual.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 12,
        description: 'Aumenta tu Velocidad de Hechizo en 20 puntos.',
        duration: 30,
        iconBuff: '/iconos/Icono-Prisa.png',

        effect: [{ bonusRef: 'vh', bonusValue: 15 }],
        price: 5000,
        idItem: IdItem.TRUCHA_ARCOIRIS_INUSUAL,
    }),

    createBuffItem({
        name: 'Trucha arcoíris (Raro)',
        img: '/itemsUtility/peces/Trucha_arcoíris_Raro.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 12,
        description: 'Aumenta tu Velocidad de Hechizo en 30 puntos.',
        duration: 60,
        iconBuff: '/iconos/Icono-Prisa.png',

        effect: [{ bonusRef: 'vh', bonusValue: 20 }],
        price: 5000,
        idItem: IdItem.TRUCHA_ARCOIRIS_RARO,
    }),

    createBuffItem({
        name: 'Trucha de río (Común)',
        img: '/itemsUtility/peces/Trucha_de_río_Común.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 13,
        description: 'Aumenta la Regeneración de HP en un 25%.',
        duration: 15,
        iconBuff: '/iconos/Icono-Restauración.png',

        effect: [{ bonusRef: 'regen_hp', bonusValue: 25 }],
        price: 1000,
        idItem: IdItem.TRUCHA_DE_RIO_COMUN,
    }),

    createBuffItem({
        name: 'Trucha de río (Inusual)',
        img: '/itemsUtility/peces/Trucha_de_río_Inusual.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 13,
        description: 'Aumenta la Regeneración de HP en un 50%.',
        duration: 30,
        iconBuff: '/iconos/Icono-Restauración.png',

        effect: [{ bonusRef: 'regen_hp', bonusValue: 50 }],
        price: 2000,
        idItem: IdItem.TRUCHA_DE_RIO_INUSUAL,
    }),

    createBuffItem({
        name: 'Trucha de río (Raro)',
        img: '/itemsUtility/peces/Trucha_de_río_Raro.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 13,
        description: 'Aumenta la Regeneración de HP en un 75%.',
        duration: 60,
        iconBuff: '/iconos/Icono-Restauración.png',

        effect: [{ bonusRef: 'regen_hp', bonusValue: 75 }],
        price: 5000,
        idItem: IdItem.TRUCHA_DE_RIO_RARO,
    }),

    createBuffItem({
        name: 'Rudd (Común)',
        img: '/itemsUtility/peces/Rudd_Común.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 14,
        description: 'Aumenta tu HP en 1000 puntos.',
        duration: 15,
        iconBuff: '/iconos/Icono-Restauración.png',

        effect: [{ bonusRef: 'hp', bonusValue: 500 }],
        price: 1000,
        idItem: IdItem.RUDD_COMUN,
    }),

    createBuffItem({
        name: 'Rudd (Inusual)',
        img: '/itemsUtility/peces/Rudd_Inusual.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 14,
        description: 'Aumenta tu HP en 2500 puntos.',
        duration: 30,
        iconBuff: '/iconos/Icono-Restauración.png',

        effect: [{ bonusRef: 'hp', bonusValue: 1000 }],
        price: 2000,
        idItem: IdItem.RUDD_INUSUAL,
    }),

    createBuffItem({
        name: 'Rudd (Raro)',
        img: '/itemsUtility/peces/Rudd_Raro.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 14,
        description: 'Aumenta tu HP en 4000 puntos.',
        duration: 60,
        iconBuff: '/iconos/Icono-Restauración.png',

        effect: [{ bonusRef: 'hp', bonusValue: 2000 }],
        price: 5000,
        idItem: IdItem.RUDD_RARO
    }),

    createBuffItem({
        name: 'Perca (Común)',
        img: '/itemsUtility/peces/Perca_Común.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 15,
        description: 'Aumenta los daños de Efecto de Estado un 10%.',
        duration: 15,
        iconBuff: '/iconos/Icono-Panacea.png',

        effect: [{ bonusRef: 'bonus_estado', bonusValue: 10 }],
        price: 1000,
        idItem: IdItem.PERCA_COMUN,
    }),

    createBuffItem({
        name: 'Perca (Inusual)',
        img: '/itemsUtility/peces/Perca_Inusual.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 15,
        description: 'Aumenta los daños de Efecto de Estado un 15%.',
        duration: 30,
        iconBuff: '/iconos/Icono-Panacea.png',

        effect: [{ bonusRef: 'bonus_estado', bonusValue: 15 }],
        price: 2000,
        idItem: IdItem.PERCA_INUSUAL,
    }),

    createBuffItem({
        name: 'Perca (Raro)',
        img: '/itemsUtility/peces/Perca_Raro.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 15,
        description: 'Aumenta los daños de Efecto de Estado un 20%.',
        duration: 60,
        iconBuff: '/iconos/Icono-Panacea.png',

        effect: [{ bonusRef: 'bonus_estado', bonusValue: 20 }],
        price: 5000,
        idItem: IdItem.PERCA_RARO,
    }),

    createBuffItem({
        name: 'Tenchi (Común)',
        img: '/itemsUtility/peces/Tenchi_Común.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 16,
        description: 'Aumenta el daño contra Monstruos un 10%.',
        duration: 15,
        iconBuff: '/iconos/Icono-Inmortal.png',

        effect: [{ bonusRef: 'monstruos', bonusValue: 10 }],
        price: 1000,
        idItem: IdItem.TENCHI_COMUN,
    }),

    createBuffItem({
        name: 'Tenchi (Inusual)',
        img: '/itemsUtility/peces/Tenchi_Inusual.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 16,
        description: 'Aumenta el daño contra Monstruos un 15%.',
        duration: 30,
        iconBuff: '/iconos/Icono-Inmortal.png',

        effect: [{ bonusRef: 'monstruos', bonusValue: 15 }],
        price: 2000,
        idItem: IdItem.TENCHI_INUSUAL,
    }),

    createBuffItem({
        name: 'Tenchi (Raro)',
        img: '/itemsUtility/peces/Tenchi_Raro.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 16,
        description: 'Aumenta el daño contra Monstruos un 20%.',
        duration: 60,
        iconBuff: '/iconos/Icono-Inmortal.png',

        effect: [{ bonusRef: 'monstruos', bonusValue: 20 }],
        price: 5000,
        idItem: IdItem.TENCHI_RARO,
    }),

    createBuffItem({
        name: 'Bagre (Común)',
        img: '/itemsUtility/peces/Bagre_Común.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 17,
        description: 'Aumenta el Daño contra Medio Humanos un 10%.',
        duration: 15,
        iconBuff: '/iconos/Icono-Inmortal.png',

        effect: [{ bonusRef: 'medio_humanos', bonusValue: 10 }],
        price: 1000,
        idItem: IdItem.BAGRE_COMUN,
    }),

    createBuffItem({
        name: 'Bagre (Inusual)',
        img: '/itemsUtility/peces/Bagre_Inusual.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 17,
        description: 'Aumenta el Daño contra Medio Humanos un 15%.',
        duration: 30,
        iconBuff: '/iconos/Icono-Inmortal.png',

        effect: [{ bonusRef: 'medio_humanos', bonusValue: 15 }],
        price: 2000,
        idItem: IdItem.BAGRE_INUSUAL,
    }),

    createBuffItem({
        name: 'Bagre (Raro)',
        img: '/itemsUtility/peces/Bagre_Raro.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 17,
        description: 'Aumenta el Daño contra Medio Humanos un 20%.',
        duration: 60,
        iconBuff: '/iconos/Icono-Inmortal.png',

        effect: [{ bonusRef: 'medio_humanos', bonusValue: 20 }],
        price: 5000,
        idItem: IdItem.BAGRE_RARO,
    }),

    createBuffItem({
        name: 'Pez loto (Común)',
        img: '/itemsUtility/peces/Pez_loto_Común.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 18,
        description: 'Aumenta la Chances de Reflectar un 10%.',
        duration: 15,
        iconBuff: '/iconos/Icono-Reflectar.png',

        effect: [{ bonusRef: 'reflectar', bonusValue: 10 }],
        price: 1000,
        idItem: IdItem.PEZ_LOTO_COMUN,
    }),

    createBuffItem({
        name: 'Pez loto (Inusual)',
        img: '/itemsUtility/peces/Pez_loto_Inusual.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 18,
        description: 'Aumenta la Chances de Reflectar un 20%.',
        duration: 30,
        iconBuff: '/iconos/Icono-Reflectar.png',

        effect: [{ bonusRef: 'reflectar', bonusValue: 15 }],
        price: 2000,
        idItem: IdItem.PEZ_LOTO_INUSUAL,
    }),

    createBuffItem({
        name: 'Pez loto (Raro)',
        img: '/itemsUtility/peces/Pez_loto_Raro.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 18,
        description: 'Aumenta la Chances de Reflectar un 30%.',
        duration: 60,
        iconBuff: '/iconos/Icono-Reflectar.png',

        effect: [{ bonusRef: 'reflectar', bonusValue: 20 }],
        price: 5000,
        idItem: IdItem.PEZ_DE_COLORES_RARO,
    }),

    createBuffItem({
        name: 'Pez dulce (Común)',
        img: '/itemsUtility/peces/Pez_dulce_Común.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 19,
        description: 'Aumenta la EXP ganada en un 10%.',
        duration: 15,
        iconBuff: '/iconos/Anillo_de_EXP.png',

        effect: [{ bonusRef: 'bonus_exp', bonusValue: 10 }],
        price: 1000,
        idItem: IdItem.PEZ_DULCE_COMUN,
    }),

    createBuffItem({
        name: 'Pez dulce (Inusual)',
        img: '/itemsUtility/peces/Pez_dulce_Inusual.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 19,
        description: 'Aumenta la EXP ganada en un 10%.',
        duration: 30,
        iconBuff: '/iconos/Anillo_de_EXP.png',

        effect: [{ bonusRef: 'bonus_exp', bonusValue: 10 }],
        price: 2000,
        idItem: IdItem.PEZ_DULCE_INUSUAL,
    }),

    createBuffItem({
        name: 'Pez dulce (Raro)',
        img: '/itemsUtility/peces/Pez_dulce_Raro.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 19,
        description: 'Aumenta la EXP ganada en un 10%.',
        duration: 60,
        iconBuff: '/iconos/Anillo_de_EXP.png',

        effect: [{ bonusRef: 'bonus_exp', bonusValue: 10 }],
        price: 5000,
        idItem: IdItem.PEZ_DULCE_RARO,
    }),

    createBuffItem({
        name: 'Pez de colores (Común)',
        img: '/itemsUtility/peces/Pez_de_colores_Común.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 19,
        description: 'Aumenta la EXP ganada en un 50%.',
        duration: 15,
        iconBuff: '/iconos/Anillo_de_EXP.png',

        effect: [{ bonusRef: 'bonus_exp', bonusValue: 50 }],
        price: 1000,
        idItem: IdItem.PEZ_DE_COLORES_COMUN,
    }),

    createBuffItem({
        name: 'Pez de colores (Inusual)',
        img: '/itemsUtility/peces/Pez_de_colores_Inusual.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 19,
        description: 'Aumenta la EXP ganada en un 50%.',
        duration: 30,
        iconBuff: '/iconos/Anillo_de_EXP.png',

        effect: [{ bonusRef: 'bonus_exp', bonusValue: 50 }],
        price: 2000,
        idItem: IdItem.PEZ_DE_COLORES_INUSUAL,
    }),

    createBuffItem({
        name: 'Pez de colores (Raro)',
        img: '/itemsUtility/peces/Pez_de_colores_Raro.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 19,
        description: 'Aumenta la EXP ganada en un 50%.',
        duration: 60,
        iconBuff: '/iconos/Anillo_de_EXP.png',

        effect: [{ bonusRef: 'bonus_exp', bonusValue: 50 }],
        price: 5000,
        idItem: IdItem.PEZ_DE_COLORES_RARO,
    }),

    createBuffItem({
        name: 'Yabby (Común)',
        img: '/itemsUtility/peces/Yabby_Común.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 19,
        description: 'Aumenta la EXP ganada en un 100%.',
        duration: 15,
        iconBuff: '/iconos/Anillo_de_EXP.png',

        effect: [{ bonusRef: 'bonus_exp', bonusValue: 100 }],
        price: 1000,
        idItem: IdItem.YABBY_COMUN,
    }),

    createBuffItem({
        name: 'Yabby (Inusual)',
        img: '/itemsUtility/peces/Yabby_Inusual.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 19,
        description: 'Aumenta la EXP ganada en un 100%.',
        duration: 30,
        iconBuff: '/iconos/Anillo_de_EXP.png',

        effect: [{ bonusRef: 'bonus_exp', bonusValue: 100 }],
        price: 2000,
        idItem: IdItem.YABBY_INUSUAL,
    }),

    createBuffItem({
        name: 'Yabby (Raro)',
        img: '/itemsUtility/peces/Yabby_Raro.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 19,
        description: 'Aumenta la EXP ganada en un 100%.',
        duration: 60,
        iconBuff: '/iconos/Anillo_de_EXP.png',

        effect: [{ bonusRef: 'bonus_exp', bonusValue: 100 }],
        price: 5000,
        idItem: IdItem.YABBY_RARO,
    }),

    createBuffItem({
        name: 'Cangrejo rey rojo (Común)',
        img: '/itemsUtility/peces/Cangrejo_rey_rojo_Común.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 20,
        description: 'Disminuye el daño recibido en un 3%.',
        duration: 15,
        iconBuff: '/iconos/Icono-Baluarte.png',

        effect: [{ bonusRef: 'damage_taken', bonusValue: -3 }],
        price: 1000,
        idItem: IdItem.CANGREJO_REY_ROJO_COMUN,
    }),

    createBuffItem({
        name: 'Cangrejo rey rojo (Inusual)',
        img: '/itemsUtility/peces/Cangrejo_rey_rojo_Inusual.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 20,
        description: 'Disminuye el daño recibido en un 5%.',
        duration: 30,
        iconBuff: '/iconos/Icono-Baluarte.png',

        effect: [{ bonusRef: 'damage_taken', bonusValue: -5 }],
        price: 2000,
        idItem: IdItem.CANGREJO_REY_ROJO_INUSUAL,
    }),

    createBuffItem({
        name: 'Cangrejo rey rojo (Raro)',
        img: '/itemsUtility/peces/Cangrejo_rey_rojo_Raro.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 50,
        idBuff: 20,
        description: 'Disminuye el daño recibido en un 7%.',
        duration: 60,
        iconBuff: '/iconos/Icono-Baluarte.png',

        effect: [{ bonusRef: 'damage_taken', bonusValue: -7 }],
        price: 5000,
        idItem: IdItem.CANGREJO_REY_ROJO_RARO,
    }),

    createBuffItem({
        name: 'Jugo Raíz Gango',
        img: '/itemsUtility/rocio/Jugo_Raíz_Gango.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 200,
        idBuff: 21,
        description: 'Disminuye el daño de Fuego recibido en un 15%.',
        duration: 20,
        iconBuff: '/iconos/Icono-Baluarte.png',
        effect: [{ bonusRef: 'def_incendio', bonusValue: 15 }],
        price: 600,
        idItem: IdItem.JUGO_RAIZ_GANGO,
    }),

    createBuffItem({
        name: 'Jugo Flor Kaki',
        img: '/itemsUtility/rocio/Jugo_Flor_Kaki.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 200,
        idBuff: 22,
        description: 'Disminuye el daño de Veneno recibido en un 15%.',
        duration: 20,
        iconBuff: '/iconos/Icono-Baluarte.png',

        effect: [{ bonusRef: 'def_veneno', bonusValue: 15 }],
        price: 600,
        idItem: IdItem.JUGO_FLOR_KAKI,
    }),

    createBuffItem({
        name: 'Jugo Harebell',
        img: '/itemsUtility/rocio/Jugo_Harebell.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 200,
        idBuff: 23,
        description: 'Disminuye el daño de Sangrado recibido en un 15%.',
        duration: 20,
        iconBuff: '/iconos/Icono-Baluarte.png',

        effect: [{ bonusRef: 'def_sangrado', bonusValue: 15 }],
        price: 600,
        idItem: IdItem.JUGO_HAREBELL,
    }),

    createBuffItem({
        name: 'Jugo Flor Melocotón',
        img: '/itemsUtility/rocio/Jugo_Flor_Melocotón.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 200,
        idBuff: 24,
        description: 'Aumenta tu Hp en 800 puntos.',
        duration: 20,
        iconBuff: '/iconos/Lectura_Concentrada.png',

        effect: [{ bonusRef: 'hp', bonusValue: 800 }],
        price: 600,
        idItem: IdItem.JUGO_FLOR_MELOCOTON,
    }),

    createBuffItem({
        name: 'Agua Sim',
        img: '/itemsUtility/rocio/Agua_Sim.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 200,
        idBuff: 25,
        description: 'Aumenta la Fuerza contra Animales en un 20%',
        duration: 20,
        iconBuff: '/iconos/Icono_daño_esp.png',

        effect: [{ bonusRef: 'animales', bonusValue: 20 }],
        price: 1250,
        idItem: IdItem.AGUA_SIM,
    }),

    createBuffItem({
        name: 'Agua Dok',
        img: '/itemsUtility/rocio/Agua_Dok.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 200,
        idBuff: 26,
        description: 'Aumenta la Fuerza contra Orcos en un 20%',
        duration: 20,
        iconBuff: '/iconos/Icono_daño_esp.png',

        effect: [{ bonusRef: 'orcos', bonusValue: 20 }],
        price: 1250,
        idItem: IdItem.AGUA_DOK,
    }),

    createBuffItem({
        name: 'Agua Bo',
        img: '/itemsUtility/rocio/Agua_Bo.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 200,
        idBuff: 27,
        description: 'Aumenta la Fuerza contra Misticos en un 20%',
        duration: 20,
        iconBuff: '/iconos/Icono_daño_esp.png',

        effect: [{ bonusRef: 'misticos', bonusValue: 20 }],
        price: 1250,
        idItem: IdItem.AGUA_BO,
    }),

    createBuffItem({
        name: 'Agua Joven',
        img: '/itemsUtility/rocio/Agua_Joven.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 200,
        idBuff: 28,
        description: 'Aumenta la Fuerza contra Demonios en un 20%',
        duration: 20,
        iconBuff: '/iconos/Icono_daño_esp.png',

        effect: [{ bonusRef: 'demonios', bonusValue: 20 }],
        price: 1250,
        idItem: IdItem.AGUA_JOVEN,
    }),

    createBuffItem({
        name: 'Agua Zin',
        img: '/itemsUtility/rocio/Agua_Zin.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 200,
        idBuff: 29,
        description: 'Aumenta la Fuerza contra Medio Humanos en un 20%',
        duration: 20,
        iconBuff: '/iconos/Icono_daño_esp.png',

        effect: [{ bonusRef: 'medio_humanos', bonusValue: 20 }],
        price: 2500,
        idItem: IdItem.AGUA_ZIN,
    }),

    createBuffItem({
        name: 'Agua Sambo',
        img: '/itemsUtility/rocio/Agua_Sambo.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 200,
        idBuff: 30,
        description: 'Aumenta la Fuerza contra Monstruos en un 20%',
        duration: 20,
        iconBuff: '/iconos/Icono_daño_esp.png',

        effect: [{ bonusRef: 'monstruos', bonusValue: 20 }],
        price: 2500,
        idItem: IdItem.AGUA_SAMBO,
    }),

    createBuffItem({
        name: 'Agua Mong',
        img: '/itemsUtility/rocio/Agua_Mong.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 200,
        idBuff: 31,
        description: 'Aumenta la Velocidad de Ataque en un 10%',
        duration: 20,
        iconBuff: '/iconos/va_Icon.png',

        effect: [{ bonusRef: 'va', bonusValue: 10 }],
        price: 2500,
        idItem: IdItem.AGUA_MONG,
    }),

    createBuffItem({
        name: 'Agua Hwal',
        img: '/itemsUtility/rocio/Agua_Hwal.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 200,
        idBuff: 32,
        description: 'Aumenta la Velocidad de Hechizo en 20 puntos.',
        duration: 20,
        iconBuff: '/iconos/Icono-Prisa.png',

        effect: [{ bonusRef: 'vh', bonusValue: 20 }],
        price: 2500,
        idItem: IdItem.AGUA_HWAL,
    }),

    createBuffItem({
        name: 'Rocío Rojo',
        img: '/itemsUtility/rocio/Rocío_Rojo.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 200,
        idBuff: 33,
        description: 'Aumenta las chances de hacer criticos en un 15%.',
        duration: 30,
        iconBuff: '/iconos/Icono_critico.png',

        effect: [{ bonusRef: 'critico', bonusValue: 15 }],
        price: 5000,
        idItem: IdItem.ROCIO_ROJO,
    }),

    createBuffItem({
        name: 'Rocío Naranja',
        img: '/itemsUtility/rocio/Rocío_Naranja.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 200,
        idBuff: 34,
        description: 'Aumenta las chances de hacer golpes penetrantes en un 15%.',
        duration: 30,
        iconBuff: '/iconos/Icono-Penetración.png',

        effect: [{ bonusRef: 'penetracion', bonusValue: 15 }],
        price: 5000,
        idItem: IdItem.ROCIO_NARANJA,
    }),

    createBuffItem({
        name: 'Rocío Amarillo',
        img: '/itemsUtility/rocio/Rocío_Amarillo.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 200,
        idBuff: 35,
        description: 'Aumenta el daño crítico un 25%.',
        duration: 30,
        iconBuff: '/iconos/Icono_critico.png',

        effect: [{ bonusRef: 'daño_critico', bonusValue: 25 }],
        price: 5000,
        idItem: IdItem.ROCIO_AMARILLO,
    }),

    createBuffItem({
        name: 'Rocío Verde',
        img: '/itemsUtility/rocio/Rocío_Verde.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 200,
        idBuff: 36,
        description: 'Aumenta el AD en 40 puntos.',
        duration: 30,
        iconBuff: '/iconos/Icono-Berserker.png',

        effect: [{ bonusRef: 'ad', bonusValue: 40 }],
        price: 5000,
        idItem: IdItem.ROCIO_VERDE,
    }),

    createBuffItem({
        name: 'Rocío Azul',
        img: '/itemsUtility/rocio/Rocío_azul.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 200,
        idBuff: 37,
        description: 'Aumenta el AP en 40 puntos.',
        duration: 30,
        iconBuff: '/iconos/Icono-Berserker.png',

        effect: [{ bonusRef: 'ap', bonusValue: 40 }],
        price: 5000,
        idItem: IdItem.ROCIO_AZUL,
    }),

    createBuffItem({
        name: 'Rocío Blanco',
        img: '/itemsUtility/rocio/Rocío_blanco.png',
        cantidad: 1,
        lvUtility: 0,
        maxCantidad: 200,
        idBuff: 38,
        description: 'Aumenta Robo de vida en un 3%.',
        duration: 30,
        iconBuff: '/iconos/Icono_robo_vida.png',

        effect: [{ bonusRef: 'robo_vida', bonusValue: 3 }],
        price: 5000,
        idItem: IdItem.ROCIO_BLANCO,
    }),
]