import { createChestItem } from "src/modules/item/factories/item-builder";
import { ChestType } from "src/modules/item/types/entities-props/chest.type";
import { IdItem } from "src/modules/item/types/iditems/id-item-list.type";

export const CHEST_LIST: ChestType[] = [
    createChestItem({
        idItem: IdItem.CAJA_DE_HABILIDADES_DE_GUERRERO,
        name: 'Caja de Habilidades de Guerrero',
        description: 'Una caja que en su interior puede tener las lecturas para el aprendizaje de una habilidad.',
        img: '/itemsUtility/hab/Caja_Guerrero.png',
        maxCantidad: 20,
        price: 1000,
        rewardConfig: 'random',
        rewards: [],
    }),
    createChestItem({
        idItem: IdItem.CAJA_DE_HABILIDADES_DE_SURA,
        name: 'Caja de Habilidades de Sura',
        description: 'Una caja que en su interior puede tener las lecturas para el aprendizaje de una habilidad.',
        img: '/itemsUtility/hab/Caja_Sura.png',
        maxCantidad: 20,
        price: 1000,
        rewardConfig: 'random',
        rewards: [],
    }),
    createChestItem({
        idItem: IdItem.CAJA_DE_HABILIDADES_DE_NINJA,
        name: 'Caja de Habilidades de Ninja',
        description: 'Una caja que en su interior puede tener las lecturas para el aprendizaje de una habilidad.',
        img: '/itemsUtility/hab/Caja_Ninja.png',
        maxCantidad: 20,
        price: 1000,
        rewardConfig: 'random',
        rewards: [],
    }),
    createChestItem({
        idItem: IdItem.CAJA_DE_HABILIDADES_DE_CHAMAN,
        name: 'Caja de Habilidades de Chaman',
        description: 'Una caja que en su interior puede tener las lecturas para el aprendizaje de una habilidad.',
        img: '/itemsUtility/hab/Caja_Chaman.png',
        maxCantidad: 20,
        price: 1000,
        rewardConfig: 'random',
        rewards: [],
    }),
    createChestItem({
        idItem: IdItem.ALMEJA,
        name: 'Caja de Habilidades de Chaman',
        description: 'Crustáceos con una cáscara bonita. Puede tener una perla en su interior..',
        img: '/itemsUtility/Almeja.png',
        maxCantidad: 20,
        price: 500,
        rewardConfig: 'random',
        rewards: [],
    }),
    createChestItem({
        idItem: IdItem.FRAGMENTO_SUPERFICIAL_NETIM,
        name: 'Fragmento Superficial Netim',
        description: 'Un fragmento superficial de una piedra Netim, aún conserva algo de su energia.',
        img: '/itemsUtility/fragmento_superficial.png',
        maxCantidad: 20,
        price: 500,
        rewardConfig: 'random',
        rewards: [],
    }),
    createChestItem({
        idItem: IdItem.FRAGMENTO_NUCLEAR_NETIM,
        name: 'Fragmento Nuclear Netim',
        description: 'Un fragmento del nucleo de una piedra Netim, emana mucha energia en su interior.',
        img: '/itemsUtility/fragmento_nuclear.png',
        maxCantidad: 20,
        price: 500,
        rewardConfig: 'random',
        rewards: [],
    }),
    createChestItem({
        idItem: IdItem.TESORO_DE_AVENTURINA,
        name: 'Tesoro de Aventurina',
        description: 'En su interior se guarda un preciado item.',
        img: '/itemsUtility/Tesoro_de_aventurina.png',
        maxCantidad: 20,
        price: 500,
        rewardConfig: 'random',
        rewards: [],
    }),
    createChestItem({
        idItem: IdItem.TESORO_DE_AUREOLINA,
        name: 'Tesoro de Aventurina',
        description: 'En su interior se guarda un preciado item.',
        img: '/itemsUtility/Tesoro_de_aureolina.png',
        maxCantidad: 20,
        price: 500,
        rewardConfig: 'random',
        rewards: [],
    }),
    createChestItem({
        idItem: IdItem.TESORO_ESTRELLADO,
        name: 'Tesoro Estrellado',
        description: 'En su interior se guarda un preciado item.',
        img: '/itemsUtility/Tesoro_estrellado.png',
        maxCantidad: 20,
        price: 500,
        rewardConfig: 'random',
        rewards: [],
    }),
]