import { ValueBonusType } from "../../types/bonus-in-item.type";
import { allFullNameBonusList } from "../../types/bonusListHelper/bonus-list-full-name.enum";
import { TierBonusType } from "../../types/bonusListHelper/bonus-list.type";

export const bonus6_7BonusList: TierBonusType[] = [
  {
    name: [allFullNameBonusList.VALOR_DE_ATAQUE, 'ad', ValueBonusType.FLAT],
    values: [10, 25],
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    name: [
      allFullNameBonusList.VALOR_DE_ATAQUE_MAGICO,
      'ap',
      ValueBonusType.FLAT,
    ],
    values: [10, 25],
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    name: [
      allFullNameBonusList.RESISTENCIA_AL_VENENO,
      'def_veneno',
      ValueBonusType.PORCENTAGE,
    ],
    values: [1, 5],
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    name: [
      allFullNameBonusList.RESISTENCIA_AL_FUEGO,
      'def_incendio',
      ValueBonusType.PORCENTAGE,
    ],
    values: [1, 5],
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    name: [
      allFullNameBonusList.RESISTENCIA_AL_SANGRADO,
      'def_sangrado',
      ValueBonusType.PORCENTAGE,
    ],
    values: [1, 5],
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    name: [
      allFullNameBonusList.FUERZA_CONTRA_CHAMANES,
      'chaman',
      ValueBonusType.PORCENTAGE,
    ],
    values: [5, 10],
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    name: [
      allFullNameBonusList.FUERZA_CONTRA_GUERREROS,
      'guerrero',
      ValueBonusType.PORCENTAGE,
    ],
    values: [5, 10],
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    name: [
      allFullNameBonusList.FUERZA_CONTRA_SURAS,
      'sura',
      ValueBonusType.PORCENTAGE,
    ],
    values: [5, 10],
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    name: [
      allFullNameBonusList.FUERZA_CONTRA_NINJAS,
      'ninja',
      ValueBonusType.PORCENTAGE,
    ],
    values: [5, 10],
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    name: [
      allFullNameBonusList.DEFENSA_CHAMAN,
      'def_chaman',
      ValueBonusType.PORCENTAGE,
    ],
    values: [3, 5],
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    name: [
      allFullNameBonusList.DEFENSA_GUERRERO,
      'def_guerrero',
      ValueBonusType.PORCENTAGE,
    ],
    values: [3, 5],
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    name: [
      allFullNameBonusList.DEFENSA_NINJA,
      'def_ninja',
      ValueBonusType.PORCENTAGE,
    ],
    values: [3, 5],
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    name: [
      allFullNameBonusList.DEFENSA_SURA,
      'def_sura',
      ValueBonusType.PORCENTAGE,
    ],
    values: [3, 5],
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    name: [allFullNameBonusList.MAX_HP, 'hp', ValueBonusType.FLAT],
    values: [50, 800],
    valid: [
      'armadura',
      'brazalete',
      'collar',
      'escudo',
      'pendiente',
      'arma',
      'botas',
      'casco',
    ],
  },
  {
    name: [
      allFullNameBonusList.VELOCIDAD_DE_ATAQUE,
      'va',
      ValueBonusType.PORCENTAGE,
    ],
    values: [1, 10],
    valid: ['arma'],
  },
  {
    name: [
      allFullNameBonusList.FUERZA_CONTRA_MONSTRUOS,
      'monstruos',
      ValueBonusType.PORCENTAGE,
    ],
    values: [5, 20],
    valid: ['collar'],
  },
  {
    name: [
      allFullNameBonusList.RESISTENCIA_AL_DAÑO_DE_HABILIDAD,
      'def_hab',
      ValueBonusType.PORCENTAGE,
    ],
    values: [1, 5],
    valid: ['armadura'],
  },
  {
    name: [
      allFullNameBonusList.RESISTENCIA_AL_DAÑO_DE_MEDIA,
      'def_media',
      ValueBonusType.PORCENTAGE,
    ],
    values: [1, 5],
    valid: ['armadura'],
  },
  {
    name: [allFullNameBonusList.STR, 'STR', ValueBonusType.FLAT],
    values: [1, 10],
    valid: ['brazalete'],
  },
  {
    name: [allFullNameBonusList.INT, 'INT', ValueBonusType.FLAT],
    values: [1, 10],
    valid: ['brazalete'],
  },
  {
    name: [allFullNameBonusList.DEX, 'DEX', ValueBonusType.FLAT],
    values: [1, 10],
    valid: ['brazalete'],
  },
  {
    name: [allFullNameBonusList.VIT, 'VIT', ValueBonusType.FLAT],
    values: [1, 10],
    valid: ['brazalete'],
  },
  {
    name: [
      allFullNameBonusList.DAÑO_ABSORBIDO_POR_HP,
      'daño_absorbido_hp',
      ValueBonusType.PORCENTAGE,
    ],
    values: [1, 5],
    valid: ['botas'],
  },
  {
    name: [
      allFullNameBonusList.PROB_DE_BLOQUEAR_ATAQUES_CUERPO_A_CUERPO,
      'bloquear_ataques',
      ValueBonusType.PORCENTAGE,
    ],
    values: [1, 10],
    valid: ['escudo'],
  },
  {
    name: [
      allFullNameBonusList.VELOCIDAD_DE_MOVIMIENTO,
      'vm',
      ValueBonusType.FLAT,
    ],
    values: [1, 20],
    valid: ['escudo'],
  },
  {
    name: [
      allFullNameBonusList.REGENERACION_DE_HP,
      'regen_hp',
      ValueBonusType.PORCENTAGE,
    ],
    values: [1, 35],
    valid: ['pendiente'],
  },
];
