import { EquipType, IdItem } from "netim2-shared";
import { createLegendaryEquipItem } from "src/modules/item/factories/item-builder";


export const BRAZALETE_LEGENDARIO_LIST: EquipType[] = [
    createLegendaryEquipItem({
        idItem: IdItem.BRAZALETE_CARRERA_DE_LA_MUERTE,
        name: 'Brazalete Carrera de la Muerte',
        lvReq: 20,
        leyenda: "Para apreciar verdaderamente la vida, debes estar presente cuando termina.",
        sub_type_equip: 'brazalete',
        especial: false,
        img: '/items/carrera_muerte.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 20000,
    }),
    createLegendaryEquipItem({
        idItem: IdItem.BRAZALETE_DE_ANDVARIUS,
        name: 'Brazalete de Andvarius',
        lvReq: 20,
        leyenda: "El peligro es el precio de la riqueza.",
        sub_type_equip: 'brazalete',
        especial: false,
        img: '/items/Andvarius.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 20000,
    }),
    createLegendaryEquipItem({
        idItem: IdItem.SORTIJA_DEL_LAZO_INQUEBRANTABLE,
        name: 'Sortija del Lazo Inquebrantable',
        lvReq: 1,
        leyenda: "Cuando la noche cae, una tenue luz se filtra por las inscripciones internas del aro, revelando palabras que ningún artesano reconoce haber grabado. Algunos aseguran que es la propia promesa, aferrándose desesperadamente a existir",
        sub_type_equip: 'brazalete',
        especial: false,
        img: '/items/anillo_compromiso.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 20000,
    }),
    createLegendaryEquipItem({
        idItem: IdItem.BRAZALETE_DE_RUBI,
        name: 'Brazalete de Rubí',
        lvReq: 40,
        leyenda: "Deja el mundo en llamas a tus espaldas.",
        sub_type_equip: 'brazalete',
        especial: false,
        img: '/items/Emberwake_inventory_icon.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 40000,
    }),
    createLegendaryEquipItem({
        idItem: IdItem.BRAZALETE_DE_ACERO_AGUIJON,
        name: 'Brazalete de Acero Aguijón',
        lvReq: 40,
        leyenda: "No es una herida causada por un enemigo que nos muerde dos veces. Es la sonrisa, el asentimiento... el apretón de manos... de un antiguo amigo.",
        sub_type_equip: 'brazalete',
        especial: false,
        img: '/items/Perandus_Signet_inventory_icon.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 40000,
    }),
    createLegendaryEquipItem({
        idItem: IdItem.BRAZALETE_DE_HIERRO_DE_VENOPUNTURA,
        name: 'Brazalete de Hierro de Venopuntura',
        lvReq: 40,
        leyenda: "Detener el flujo de sangre es ahogar la lluvia en las mismas nubes.",
        sub_type_equip: 'brazalete',
        especial: false,
        img: '/items/Venopuncture_inventory_icon.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 40000,
    }),
    createLegendaryEquipItem({
        idItem: IdItem.BRAZALETE_DE_AGARRE_TEMPORAL,
        name: 'Brazalete de Agarre Temporal',
        lvReq: 40,
        leyenda: "Solo cuando la mente está vacía de ambición puede la fría verdad de la existencia apoderarse.",
        sub_type_equip: 'brazalete',
        especial: false,
        img: '/items/The_Taming_inventory_icon.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 40000,
    }),
    createLegendaryEquipItem({
        idItem: IdItem.BRAZALETE_SIN_NOMBRE,
        name: 'Brazalete Sin Nombre',
        lvReq: 60,
        leyenda: "Calma tu alma turbada. No pienses. Solo ora... a mí.",
        sub_type_equip: 'brazalete',
        especial: false,
        img: '/items/anillo_sin_nombre.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 60000,
    }),
    createLegendaryEquipItem({
        idItem: IdItem.BRAZALETE_DEL_ACUSADOR_ODIOSO,
        name: 'Brazalete del Acusador Odioso',
        lvReq: 60,
        leyenda: "La historia enseña humildad.",
        sub_type_equip: 'brazalete',
        especial: false,
        img: '/items/acusador_odioso.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 60000,
    }),
]