import { createLegendaryEquipItem } from "src/modules/item/factories/item-builder";
import { EquipType } from "src/modules/item/types/entities-props/equip.type";
import { IdItem } from "src/modules/item/types/iditems/id-item-list.type";

export const COLLAR_LEGENDARIO_LIST: EquipType[] = [
    createLegendaryEquipItem({
        idItem: IdItem.ASTRAMENTIS,
        name: 'Astramentis',
        lvReq: 40,
        leyenda: "La furia irracional sacudirá el mundo, las mentiras astutas lo doblegarán.",
        sub_type_equip: 'collar',
        especial: false,
        img: '/items/Astramentis_inventory_icon.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 40000,
    }),
    createLegendaryEquipItem({
        idItem: IdItem.COLLAR_TURQUESA_DE_ARMONIA,
        name: 'Collar Turquesa de Armonía',
        lvReq: 20,
        leyenda: "Ira suave, calma furiosa.",
        sub_type_equip: 'collar',
        especial: false,
        img: '/items/Ungils_Harmony_inventory_icon.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 20000,
    }),
    createLegendaryEquipItem({
        idItem: IdItem.COLLAR_DE_LA_FALACIA,
        name: 'Collar de la Falacia',
        lvReq: 60,
        leyenda: "Quien se encuentra en la cima más alta está destinado a ser visto...",
        sub_type_equip: 'collar',
        especial: false,
        img: '/items/Marylenes_Fallacy_inventory_icon.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 60000,
    }),
    createLegendaryEquipItem({
        idItem: IdItem.COLLAR_DE_BISCO,
        name: 'Collar de Bisco',
        lvReq: 40,
        leyenda: "Una amistad que vale su peso en oro, un tesoro cada día.",
        sub_type_equip: 'collar',
        especial: false,
        img: '/items/Biscos_Collar_inventory_icon.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 40000,
    }),
    createLegendaryEquipItem({
        idItem: IdItem.COLLAR_DE_CORAL_ARAKU_TIKI,
        name: 'Collar de Coral Araku Tiki',
        lvReq: 20,
        leyenda: "Se dice que te hace invisible cuando el Gran Espíritu viene a llevarte en tu viaje final.",
        sub_type_equip: 'collar',
        especial: false,
        img: '/items/Araku_Tiki_inventory_icon.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 20000,
    }),
]