import { EquipType, IdItem } from "netim2-shared";
import { createLegendaryEquipItem } from "src/modules/item/factories/item-builder";


export const ESCUDO_LEGENDARIO_LIST: EquipType[] = [
    createLegendaryEquipItem({
        idItem: IdItem.ESCUDO_ESPIRITUAL,
        name: 'Escudo Espiritual',
        lvReq: 60,
        leyenda: "No te inmutes. Es una pérdida de tiempo para atacar.",
        sub_type_equip: 'escudo',
        especial: false,
        img: '/items/escudo_espiritual.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 60000,
    }),
    createLegendaryEquipItem({
        idItem: IdItem.ESCUDO_REFLEJO_DORADO,
        name: 'Escudo Reflejo Dorado',
        lvReq: 20,
        leyenda: "La carga de uno es el regalo de otro.",
        sub_type_equip: 'escudo',
        especial: false,
        img: '/items/escudo_dorado_reflejo.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 20000,
    }),
    createLegendaryEquipItem({
        idItem: IdItem.ESCUDO_CORRUGADO_DE_LA_PROTECCION,
        name: 'Escudo Corrugado de la Protección',
        lvReq: 60,
        leyenda: "Los horrores que hemos encontrado no son nada comparados con los horrores que no hemos encontrado.",
        sub_type_equip: 'escudo',
        especial: false,
        img: '/items/escudo_corrugado.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 60000,
    }),
    createLegendaryEquipItem({
        idItem: IdItem.ESCUDO_FAUCES_DE_LA_AGONIA,
        name: 'Escudo Fauces de la Agonía',
        lvReq: 40,
        leyenda: "Un paso en falso desencadena la destrucción. La agonía domina lentamente la voluntad de vivir.",
        sub_type_equip: 'escudo',
        especial: false,
        img: '/items/fauces_de_la_agonia.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 40000,
    }),
    createLegendaryEquipItem({
        idItem: IdItem.EL_OPRESOR,
        name: 'El Opresor',
        lvReq: 40,
        leyenda: "Nunca dejes que el público conozca tu verdadera forma. Desorienta, seduce. Ataca cuando menos lo esperen.",
        sub_type_equip: 'escudo',
        especial: false,
        img: '/items/opresor.png',
        slot: 0,
        size: { rows: 1, cols: 1 },
        price: 40000,
    }),
]